folio-org/stripes-acq-components

.editorconfig, .eslintrc, .gitignore, CHANGELOG.md, CONTRIBUTING.md, LICENSE, PULL_REQUEST_TEMPLATE.md, README.md, index.js, lib/FieldSelection/FieldSelection.js, lib/FieldSelection/index.js, lib/index.js, package.json
* initial setup of stripes module;
* `SelectionField` component
=> UINV-25 SelectionField and module setup

lib/AcqCheckboxFilter/AcqCheckboxFilter.js, lib/AcqCheckboxFilter/index.js, lib/FieldSelection/FieldSelection.js, lib/OrganizationFilter/OrganizationFilter.js, lib/OrganizationFilter/index.js, lib/SelectionFilter/SelectionFilter.js, lib/SelectionFilter/index.js, lib/index.js, lib/shapes/index.js, lib/shapes/organization.js, lib/shapes/selectOptions.js, lib/utils/createClearFilterHandler.js, lib/utils/createOnChangeSelectionFilter.js, lib/utils/filterSelectValues.js, lib/utils/getOrganizationsOptions.js, lib/utils/index.js, lib/utils/searchAndSort.js, lib/utils/showToast.js, package.json
Some common filter components and util functions.
https://issues.folio.org/browse/UINV-26 …
=> UINV-26 search and filter common code

lib/SourceFilter/SourceFilter.js, lib/SourceFilter/index.js, lib/constants/index.js, lib/constants/source.js, lib/index.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIOR-268
Add list of options for `Source`: User, API, EDI, MARC …
=> UIOR-268 Add enum options for Source

lib/FieldSelection/FieldSelection.js
To remove warning in console, 
> ERROR: 'Warning: Failed prop type: The prop `name` is marked as required in `Field`, but its value is `undefined`.
in Field (created by FieldSelection)
in FieldSelection (created by ConnectedField)
in ConnectedField (created by Connect(ConnectedField))
in Connect(ConnectedField) (created by Field)
in Field
in div (created by Col)
in Col
in div (created by Row)
in Row
in div (created by Col)
in Col
in div (created by Row)
in Row
in Unknown (created by ConnectedFieldArray)
in ConnectedFieldArray (created by Connect(ConnectedFieldArray))
in Connect(ConnectedFieldArray) (created by FieldArray)
in FieldArray (created by ContributorForm)
in ContributorForm (created by ItemForm)
in div (created by Col)
in Col (created by ItemForm)
in div (created by Row)
in Row …
=> Fix name is required warning

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/zh_CN.json
=> Update translation strings as of 20190709T154346

test/bigtest/helpers/prefixKeys.js
A helper function to support prefixing translations for tests …
=> add prefix helper

lib/AmountWithCurrencyField/AmountWithCurrencyField.js, lib/AmountWithCurrencyField/index.js, lib/index.js, lib/utils/getAmountWithCurrency.js, lib/utils/index.js
https://issues.folio.org/browse/UIOR-123
Create a common component `AmountWithCurrencyField` to show amount with currency sign
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
=> UIOR-123 Add common component to show amount with currency sign

translations/stripes-acq-components/pt_BR.json
=> Update translation strings as of 20190711T172340

lib/FieldSelect/FieldSelect.js, lib/FieldSelect/index.js, lib/FieldSelection/FieldSelection.js, lib/index.js, translations/stripes-acq-components/en.json
=> UINV-14 FieldSelect

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/zh_CN.json
=> Update translation strings as of 20190729T163855

lib/utils/index.js, lib/utils/validateRquired.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIOR-335
Default validation for require field
While it's …
=> UIOR-335 add validation

lib/FieldAutoSuggest/FieldAutoSuggest.js, lib/FieldAutoSuggest/index.js, lib/index.js
While refactoring the ticket I think it would be nice to use a common component for autocomplete feature and leverage it to out acq repo.
https://issues.folio.org/browse/UIORGS-71
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
=> UIORGS-71 added `FieldAutoSuggest` component

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/zh_CN.json
=> Update translation strings as of 20190801T134041

lib/AcqUnits/AcqUnits.js
https://issues.folio.org/browse/UIOR-300 …
=> UIOR-300 acq units component - fix query

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/zh_CN.json
=> Update translation strings as of 20190807T131714

lib/AcqUnits/AcqUnitsField/AcqUnitsFieldContainer.js
https://issues.folio.org/browse/UIAC-4
change condition …
=> UIAC-4 fix acq units disable condition

lib/AcqUnits/AcqUnitsView/AcqUnitsView.js, lib/AcqUnits/AcqUnitsView/AcqUnitsViewContainer.js, lib/AcqUnits/AcqUnitsView/index.js, lib/AcqUnits/index.js
https://issues.folio.org/browse/UIAC-8
new component …
=> UIAC-8 AcqUnitsView component

lib/utils/getConfigSetting.js, lib/utils/index.js
https://issues.folio.org/browse/UINV-22
Add function for get config value
While it's …
=> UINV-22 add function for get config

lib/FileUploader/FileUploader.css, lib/FileUploader/FileUploader.js, lib/FileUploader/index.js, lib/index.js, lib/utils/downloadBase64.js, lib/utils/index.js, package.json, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UINV-15 …
=> UINV-15 file uploader / download base64

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/zh_CN.json
=> Update translation strings as of 20190819T080537

.eslintrc, package.json
To cover code with eslint rules on React Hooks …
=> Introduce eslint rules for React Hooks

lib/AcqUnits/AcqUnitsField/AcqUnitsFieldContainer.js
https://issues.folio.org/browse/UIOR-338
change manifest name …
=> UIOR-338 Wrong acquisition units displaying in 3rd pane of search/sort

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/pt_BR.json
=> Update translation strings as of 20190823T083240

lib/hooks/index.js, lib/hooks/useModalToggle.js, lib/hooks/useShowToast.js, lib/index.js
https://issues.folio.org/browse/UINV-62 …
=> UINV-62 hooks for callout and modal toggle

lib/PluginFindRecord/Filters.js, lib/PluginFindRecord/PluginFindRecord.css, lib/PluginFindRecord/PluginFindRecord.js, lib/PluginFindRecord/PluginFindRecordModal.css, lib/PluginFindRecord/PluginFindRecordModal.js, lib/PluginFindRecord/index.js, lib/index.js, package.json, translations/stripes-acq-components/en.json, translations/stripes-acq-components/en_US.json
it's a common code to reuse by ui-plugin-find-* based on
`SearchAndSortQuery`
it's a common code to reuse by ui-plugin-find-* based on `SearchAndSortQuery`.
So to fix next 3 tickets we have to refactor some plugins to use SearchAndSortQuery
https://issues.folio.org/browse/UIORGS-87
https://issues.folio.org/browse/UIOR-345
https://issues.folio.org/browse/UIOR-349
- Do PRs exist for these …
=> UIORGS-87 PluginFindRecord component

lib/FolioFormattedDate/FolioFormattedDate.js, lib/FolioFormattedDate/index.js, lib/index.js
Create a common component for displaying date. …
=> UIF-92 Create common component for date

lib/PluginFindRecord/PluginFindRecord.css, lib/PluginFindRecord/PluginFindRecord.js, lib/PluginFindRecord/PluginFindRecordModal.js
some styles were missed, and no need in footer if it's not multiselect mode
https://issues.folio.org/browse/UIOR-345 …
=> UIOR-345 add missing styles and hide footer if it's not multiselect

lib/hooks/index.js, lib/hooks/useAccordionToggle.js
=> UIF-92 Add hook for accordion toggle

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/zh_CN.json
=> Update translation strings as of 20190903T134424

lib/PluginFindRecord/PluginFindRecord.js, lib/PluginFindRecord/PluginFindRecordModal.css, lib/PluginFindRecord/PluginFindRecordModal.js, lib/PluginFindRecord/readme.md
Added readme, fixed checkboxes re-renders after click, added `renderTrigger` prop
https://issues.folio.org/browse/UIOR-349 …
=> UIOR-349 fix checkboxes, add readme

lib/PluginFindRecord/PluginFindRecord.js
https://issues.folio.org/browse/UIF-56 …
=> UINV-56 fix eslint

lib/PluginFindRecord/PluginFindRecordModal.js
It's a proper fix port from https://issues.folio.org/browse/UIPFU-21  …
=> Fix adoptation from UIPFU-21

lib/FieldTags/FieldTags.js, lib/FieldTags/FieldTagsContainer.js, lib/FieldTags/index.js, lib/index.js, lib/utils/filterArrayValues.js, lib/utils/index.js, package.json, translations/stripes-acq-components/en.json
Create common component `FieldTags` …
=> UIF-79 Add common component for tags

lib/FolioFormattedDate/FolioFormattedDate.js
To make date format consistent across Acq modules
https://issues.folio.org/browse/UIOR-330 …
=> UIOR-330 make consistent date format 'YYYY-MM-DD'

lib/AcqList/SingleSearchForm/SingleSearchForm.js
https://issues.folio.org/browse/UIF-96 …
=> UIF-96 fix SingleSearchForm ariaLabelId prop

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/zh_CN.json
=> Update translation strings as of 20190918T144452

translations/stripes-acq-components/it_IT.json
=> Update translation strings as of 20190919T124724

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/pt_BR.json
=> Update translation strings as of 20190925T125755

lib/AcqUnits/AcqUnits.css, lib/AcqUnits/AcqUnitsField/AcqUnitsField.js, lib/AcqUnits/AcqUnitsField/AcqUnitsFieldContainer.js, lib/AcqUnits/AcqUnitsView/AcqUnitsView.js, lib/AcqUnits/AcqUnitsView/AcqUnitsViewContainer.js
https://issues.folio.org/browse/UIOR-365 …
=> UIOR-365 Support isDeleted property of Acq units

lib/FieldDatepicker/FieldDatepicker.js, lib/FieldSelect/FieldSelect.js, lib/FieldSelection/FieldSelection.js, lib/FundDistribution/FundDistributionFields/FundDistributionFields.js, lib/shapes/fieldSelectOptions.js, lib/shapes/index.js, lib/shapes/selectOptions.js
It fixes warnings in the console …
=> fix console warnings

lib/FieldSelect/FieldSelect.js, lib/FieldSelection/FieldSelection.js
to fix warnings regarding wrong attr `validate` provided to `Field` component
While it's …
=> fix warnings regarding wrong attr `validate`

lib/index.js
Export `SelectionFilter` to use in `FundsList`
https://issues.folio.org/browse/UIF-112 …
=> UIF-112 Export Selection filter

test/bigtest/network/factories/user.js
extend user factory in tests, so it could be re-used in ui-orders …
=> extend user factory

test/bigtest/network/configs/index.js, test/bigtest/network/configs/utils.js
usually we copy-paste mirage config handlers for common CRUD operations.
While it's …
=> add BigTest Mirage common config handlers

test/bigtest/network/configs/utils.js
return 404 response if record was not found in test DB …
=> add 404 response on absent record

translations/stripes-acq-components/ar.json
=> Update translation strings as of 20191004T135530

lib/constants/index.js, lib/constants/paymentMethod.js, translations/stripes-acq-components/en.json
Add translatable payment methods options …
=> UIORGS-84 Add translatable payment methods options

lib/AcqCheckboxFilter/AcqCheckboxFilter.js
Extend acqCheckbox filter to use options like
- `{label: <FormattedMessage id={'label'} />, value}`
- `{labelId: 'label', value}` …
=> Extend acqCheckbox filter

test/bigtest/interactors/controls/MultiSelectionInteractor.js, test/bigtest/interactors/controls/index.js
To remove `stripes-components` from deps of ui-orders …
=> add MultiSelection interactor

lib/FieldTags/FieldTagsContainer.js, lib/Tags/TagsBadge/TagsBadge.js, lib/Tags/TagsBadge/TagsBadgeContainer.js, lib/Tags/TagsBadge/index.js, lib/Tags/TagsContainer.js, lib/Tags/TagsForm.js, lib/Tags/index.js, lib/constants/api.js, lib/index.js, lib/manifests/index.js, lib/manifests/tags.js
To display, assign, unassign, and output tags associated with individual ORDER LINE records within the FOLIO Orders app
https://issues.folio.org/browse/UIOR-5
Transfer code for tags from `ui-invoce` to `stripes-acq-components` to create common `Tags` component to use it for invoice lines and order lines
Ideally all of the PRs involved in breaking changes …
=> UIOR-5 Assign tags to Order Line Records

lib/FieldSelection/FieldSelection.js, lib/FundDistribution/FundDistributionFields/FundDistributionFields.js, lib/RepeatableFieldWithErrorMessage/RepeatableFieldWithErrorMessage.css, lib/RepeatableFieldWithErrorMessage/RepeatableFieldWithErrorMessage.js, lib/RepeatableFieldWithErrorMessage/index.js, lib/index.js, lib/shapes/fundDistributionShape.js, lib/utils/validateFundDistribution.js
On integration phase it was discovered that validation throws UI errors. So it was re-implemented with a proxy component for repeatable fields with error message. 
https://issues.folio.org/browse/UINV-68 …
=> UINV-68 fix error message and validation

lib/FundDistribution/FundDistributionView/FundDistributionView.js, lib/FundDistribution/FundDistributionView/FundDistributionViewContainer.js, lib/utils/validateFundDistribution.js, translations/stripes-acq-components/en.json
* Add validation for total amount
* fix View of distributions
https://issues.folio.org/browse/UINV-68 …
=> UINV-68 add validation for total amount

lib/Tags/TagsBadge/TagsBadge.js, lib/Tags/TagsForm.js, translations/stripes-acq-components/en.json
=> Fix Tags translations

lib/utils/batchFetch.js, lib/utils/index.js
https://issues.folio.org/browse/UIOR-377 …
=> UIOR-377 batchFetch util

lib/CurrencySymbol/CurrencySymbol.js, lib/CurrencySymbol/index.js, lib/FundDistribution/FundDistributionFields/FundDistributionFields.js, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsContainer.js, lib/index.js, translations/stripes-acq-components/en.json
=> UIOR-370 display currency symbol

lib/AcqTagsFilter/AcqTagsFilter.js, lib/AcqTagsFilter/index.js, lib/index.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIOR-275 …
=> UIOR-275 AcqTagsFilter component

lib/AcqTagsFilter/AcqTagsFilter.js
https://issues.folio.org/browse/UIOR-275 …
=> UIOR-275 AcqTagsFilter use default labelId

lib/FieldMultiSelection/FieldMultiSelection.js
=> clean-up multiselection

lib/AcqUnits/AcqUnitsView/AcqUnitsViewContainer.js
Fix issue of duplicating units
https://issues.folio.org/browse/UIF-72 …
=> UIF-72 fix dups of units on create and edit

lib/FundDistribution/FundDistributionFields/FundDistributionFieldsContainer.js, lib/FundDistribution/FundDistributionView/FundDistributionViewContainer.js, lib/constants/api.js, lib/manifests/fund.js, lib/manifests/index.js, package.json
to be able assign acq untis to funds we need to change the API to business layer (mod-finance)
https://issues.folio.org/browse/UIF-72 …
=> UIF-72 change FUNDS api to BL

test/bigtest/network/configs/funds.js, test/bigtest/network/configs/units.js
some improvements to the mirage configs of funds and acq units …
=> improve mirage configs

lib/FundDistribution/FundDistributionView/FundDistributionView.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIOR-425
use MCL …
=> UIOR-425 Update view for Fund distribution information on Order

lib/AcqUnits/AcqUnitsField/AcqUnitsField.js, lib/AcqUnits/AcqUnitsField/AcqUnitsFieldContainer.js, lib/FieldMultiSelection/FieldMultiSelectionFinal.js, lib/FieldMultiSelection/index.js, lib/FieldSelection/FieldSelectionFinal.js, lib/FieldSelection/index.js, package.json
Switch to react-final-form requires to use `Field` from appropriate package. So I've added some components, that required in Fund form …
=> UIF-34 add react-final-form components

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/ru.json, translations/stripes-acq-components/zh_CN.json, translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20191028T151017

test/bigtest/interactors/controls/TextFieldInteractor.js, test/bigtest/network/configs/funds.js, test/bigtest/network/cql.js
Sometimes we need to support filtering by CQL (like in Fund form, to validate if funds with name or code are exist). …
=> UIF-34 add fitlering CQL for funds

test/bigtest/network/configs/funds.js
=> fix funds bigtest mirage config

lib/FieldTags/FieldTags.js
=> UIOR-342 remove hardcoded name from FieldTags

lib/CountryFilter/CountryFilter.js, lib/LanguageFilter/LanguageFilter.js
Fix prop types
While it's helpful for reviewers to help identify potential problems, …
=> UIORGS-90 Fix prop types

lib/FundDistribution/FundDistributionFields/FundDistributionFields.js
Fix to change the type of fund distribution from the first click …
=> Fix of clicking twice to change the fund distribution type

test/bigtest/network/factories/fund.js
=> UIF-132 Update fund factory

translations/stripes-acq-components/it_IT.json
=> Update translation strings as of 20191112T144117

translations/stripes-acq-components/ru.json
=> Update translation strings as of 20191113T152522

test/bigtest/network/factories/fund.js
Fix fund mirage factory
https://issues.folio.org/browse/UIF-98 …
=> UIF-98 fix Bigtest Mirage factory for composite fund

lib/constants/constants.js, lib/hooks/useShowToast.js, lib/utils/showToast.js
Previous way to display toasts allows only message id from the translation file. However, it might be very useful to be able using `message` as `FormattedMessage` itself , with `defaultMessage` in it. …
=> UIF-98 to show error with defaultMessage we need improved showCallout

lib/utils/validateFundDistribution.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UINV-87 …
=> UINV-87 multiple distributions for the same Fund validation

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/he.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/ja.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/ru.json, translations/stripes-acq-components/zh_CN.json, translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20191118T154404

test/bigtest/helpers/turn-off-warnings.js
=> suppress react warnings in tests

translations/stripes-acq-components/fr_FR.json
=> Update translation strings as of 20191119T231120

lib/Tags/TagsContainer.js, test/bigtest/network/configs/tags.js, test/bigtest/network/factories/fund.js, test/bigtest/network/factories/index.js, test/bigtest/network/factories/tag.js, test/bigtest/network/models/index.js, test/bigtest/network/models/tag.js, test/bigtest/network/serializers/index.js, test/bigtest/network/serializers/tag.js
https://issues.folio.org/browse/UIF-18 …
=> UIF-18 Update fund factory, add Loading for Tags

lib/AcqTagsFilter/AcqTagsFilter.js
https://issues.folio.org/browse/UIF-127 …
=> UIF-127 remove active filters values

lib/AcqUnits/AcqUnitsView/AcqUnitsView.js
=> fix warning

translations/stripes-acq-components/en.json
=> add missed country

CHANGELOG.md, lib/AcqUnits/AcqUnitsView/AcqUnitsViewContainer.js, lib/CurrencySymbol/CurrencySymbol.js, lib/FolioFormattedDate/FolioFormattedDate.js, package.json
https://issues.folio.org/browse/UINV-86 …
=> Release v1.3.0

lib/utils/batchFetch.js
Add common buildQuery callback for batchFetch to filter items by ids
https://issues.folio.org/browse/UIORGS-122 …
=> UIORGS-122 Add common buildQuery callback for batchFetch

lib/utils/validateRequired.js, translations/stripes-acq-components/en.json
Add common validation for not negative values
https://issues.folio.org/browse/UINV-94 …
=> UINV-94 Add valitadion for not negative values

lib/utils/parseNumberFieldValue.js, lib/utils/validateRequired.js
Add validation for numbers
https://issues.folio.org/browse/UINV-94 …
=> UINV-94 Add validation for numbers

lib/PluginFindRecord/PluginFindRecord.js, lib/PluginFindRecord/PluginFindRecordModal.js, package.json
https://issues.folio.org/browse/UIPFPOL-3
https://issues.folio.org/browse/ERM-620
Pass refs to Modal and the trigger button so that they could be used to focus the trigger button before opening and after closing a modal.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> Pass refs to Modal and trigger button, refs UIPFPOL-3

.eslintrc, lib/FundDistribution/FundDistributionFields/FundDistributionFields.js, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsContainer.js, lib/FundDistribution/FundDistributionView/FundDistributionView.js, lib/FundDistribution/FundDistributionView/FundDistributionViewContainer.js, lib/utils/calculateFundAmount.js, lib/utils/calculateFundAmount.test.js, lib/utils/calculateFundDistributionTotal.js, lib/utils/calculateFundDistributionTotal.test.js, lib/utils/getMoneyMultiplier.js, lib/utils/getMoneyMultiplier.test.js, lib/utils/index.js, lib/utils/validateFundDistribution.js
To handle math right in JS we have to operate with integers and use Math.round where needed. This change introduces common calculate functions and their usage in Fund distribution an validation
https://issues.folio.org/browse/UIOR-464 …
=> UIOR-464 add correct currency calculation functions

CHANGELOG.md, PULL_REQUEST_TEMPLATE.md
=> add changelog

.eslintignore, CHANGELOG.md, package.json
to support patch releases
https://issues.folio.org/browse/UIOR-469
https://issues.folio.org/browse/UINV-95 …
=> Release v1.3.1

lib/FundDistribution/FundDistributionFields/FundDistributionFields.js, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsContainer.js, lib/FundDistribution/FundDistributionView/FundDistributionView.js, lib/FundDistribution/FundDistributionView/FundDistributionViewContainer.js
`currency` prop could came as `null` or blank string, also we don't need to pass the whole `stripes` prop to the View component
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
=> UIOR-460 simplify and reduce `stripes` prop usage

CHANGELOG.md, lib/manifests/index.js, lib/manifests/organizations.js
to share Organizations manifest …
=> UIOR-478 add organizations manifest

CHANGELOG.md, package.json
=> Release v1.3.2

CHANGELOG.md, lib/AcqList/ResultsPane/ResultsPane.js
render button `new` in the list
https://issues.folio.org/browse/UIREC-28 …
=> UIREC-28 Render button New in records list

lib/FieldSelect/FieldSelect.js, lib/FieldSelect/FieldSelectFinal.js, lib/FieldSelect/index.js, lib/hooks/useShowToast.js, lib/utils/showToast.js
=> SelectField for final-form, depracted useToast

lib/FormFooter/FormFooter.js, lib/FormFooter/index.js, lib/index.js, translations/stripes-acq-components/en.json
Due to work on https://issues.folio.org/browse/UIREC-28 we need to move a common component of FormFooter to the lib repo …
=> UIREC-28 move form footer component from ui-invoice

lib/manifests/contributorNameTypes.js, lib/manifests/identifierTypes.js
=> sort by name by default

lib/FormFooter/FormFooter.js
=> add margin at bottom

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/he.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/ja.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/ru.json, translations/stripes-acq-components/zh_CN.json, translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20200109T152437

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/pt_BR.json
=> Update translation strings as of 20200110T211826

lib/AcqList/SingleSearchForm/SingleSearchForm.js, lib/AcqList/constants.js, lib/AcqList/hooks/useFilters.js, lib/AcqList/hooks/useLocationFilters.js, lib/AcqList/utils/queryUtils.js, lib/AcqList/utils/searchUtils.js
To support search indexes in 3-panes-layout's search.
use like this:
```
const searchableIndexes = [
{
label: 'keyword',
value: '',
},
{
label: 'title',
value: 'title',
},
];
const [
...
changeIndex,
searchIndex,
] = useLocationFilters(location, history, resetData);
<SingleSearchForm
...
searchableIndexes={searchableIndexes}
changeSearchIndex={changeIndex}
selectedIndex={searchIndex}
/>
```
- Do JIRAs exist to update the impacted …
=> UIORGS-130 search indexes support

lib/Tags/TagsPane.js, lib/Tags/index.js
=> UIORGS-130 tags pane

lib/AcqList/ResultsPane/FilterPaneToggle.js, lib/AcqList/ResultsPane/ResultsPane.js, lib/hooks/index.js, lib/hooks/useToggle.js
=> UIORGS-130 filters toggle

lib/AcqList/utils/queryUtils.js
=> UIORGS-130 AcqList default sorting

lib/AcqList/SingleSearchForm/SingleSearchForm.js
=> UIORGS-130 SingleSearchForm - indexes translation

lib/AcqList/hooks/useFilters.js, lib/AcqList/hooks/useLocationFilters.js
To make linter happy and avoid unused methods assignment from the custom hook …
=> UIORGS-130 return object from useFilters hook

CHANGELOG.md, lib/FieldDatepicker/FieldDatePickerFinal.js, lib/FieldDatepicker/index.js
Add Field Datepicker for react-final-form
https://issues.folio.org/browse/UIREC-32
While …
=> UIREC-32 Add Field Datepicker for react-final-form

lib/FieldDatepicker/FieldDatepicker.js
Update datepicker field for using with react-final-form …
=> Update datepicker field for using with react-final-form

translations/stripes-acq-components/fr_FR.json
=> Update translation strings as of 20200117T173544

lib/SelectionFilter/SelectionFilter.js
to reduce number of console warnings …
=> fix same id console warning

lib/constants/order.js, lib/manifests/location.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIREC-29 …
=> UIREC-39 add missed translations

test/bigtest/network/configs/index.js, test/bigtest/network/configs/locations.js, test/bigtest/network/configs/materialTypes.js, test/bigtest/network/factories/index.js, test/bigtest/network/factories/location.js, test/bigtest/network/factories/material-type.js, test/bigtest/network/models/index.js, test/bigtest/network/models/location.js, test/bigtest/network/models/material-type.js, test/bigtest/network/serializers/index.js, test/bigtest/network/serializers/location.js, test/bigtest/network/serializers/material-type.js
=> materialType and location config

package.json, test/bigtest/network/configs/users.js, test/bigtest/network/configs/utils.js, test/bigtest/network/factories/fund.js, test/bigtest/network/factories/location.js, test/bigtest/network/factories/material-type.js, test/bigtest/network/factories/tag.js, test/bigtest/network/factories/unit.js, test/bigtest/network/factories/user.js, test/bigtest/network/factories/vendor.js, test/bigtest/network/models/fund.js, test/bigtest/network/models/location.js, test/bigtest/network/models/material-type.js, test/bigtest/network/models/tag.js, test/bigtest/network/models/unit.js, test/bigtest/network/models/user.js, test/bigtest/network/models/vendor.js, test/bigtest/network/modules.js, test/bigtest/network/serializers/base.js
switch to the new mock server with hope it helps to rid of random timeout test failures
https://github.com/folio-org/stripes-core/pull/783 …
=> switch to miragejs bigtest mirage mock server

test/.eslintrc
=> update eslint rule for tests code

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/he.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/ja.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/ru.json, translations/stripes-acq-components/zh_CN.json, translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20200127T144839

CHANGELOG.md, lib/PluginFindRecord/PluginFindRecordModal.js
Fix minor issues
https://issues.folio.org/browse/UIORGS-112 …
=> Uiorgs 112 disable sorting of checkboxes

lib/AcqList/FiltersPane/FiltersPane.js
=> add attribute for testing purposes

lib/AcqList/SingleSearchForm/SingleSearchForm.js
tests support
While it's helpful for reviewers to help identify potential problems, ensuring …
=> add another test attr

lib/constants/api.js, test/bigtest/network/configs/index.js, test/bigtest/network/configs/lines.js, test/bigtest/network/factories/index.js, test/bigtest/network/factories/line.js, test/bigtest/network/models/line.js, test/bigtest/network/serializers/index.js, test/bigtest/network/serializers/line.js
Add poLine `Model`, `Factory`, `Config`, `Serializer` to BigTest network for common usage …
=> Add line to BigTest network for common usage

CHANGELOG.md, lib/FundDistribution/FundDistributionView/FundDistributionView.js, lib/FundDistribution/FundDistributionView/FundDistributionViewContainer.js, lib/constants/api.js, lib/manifests/index.js, lib/manifests/transactions.js, package.json, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIOR-472 …
=> UIOR-472 Display encumbered value on POL for orders made in currency other than system currency

lib/manifests/transactions.js, test/bigtest/network/configs/index.js, test/bigtest/network/configs/transactions.js, test/bigtest/network/factories/transaction.js, test/bigtest/network/models/transaction.js, test/bigtest/network/serializers/transaction.js
* add `transactions` bigtest mirage config;
* disable fetching of transactions right away, since it's done in the useEffect; …
=> add transactions for bigtest

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/he.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/ja.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/ru.json, translations/stripes-acq-components/zh_CN.json, translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20200202T214053

CHANGELOG.md, lib/Organization/OrganizationValue/OrganizationValue.js, lib/Organization/OrganizationValue/OrganizationValue.test.js, lib/Organization/OrganizationValue/index.js, lib/Organization/index.js, lib/index.js, lib/manifests/organizations.js, test/jest/__mock__/index.js, test/jest/__mock__/stripesCore.mock.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIOR-358 …
=> UIOR-358 OrganizationValue component

lib/Tags/TagsContainer.js, lib/Tags/TagsForm.js, translations/stripes-acq-components/en.json
* to not make a PUT call for the item with tags that were not changed;
* to provide additional callout that tag was not added;
https://issues.folio.org/browse/STCOM-579
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> STCOM-579 add more callouts

test/jest/__mock__/documentCreateRange.mock.js, test/jest/__mock__/index.js
=> document.createRange mock

lib/hooks/useShowToast.js
To improve useCallout hook and to not return a new fn every time …
=> Memoize useCallout hook

translations/stripes-acq-components/ar.json
=> Update translation strings as of 20200211T224145

lib/OrganizationFilter/PluggableOrganizationFilter.js
=> fix non-unique id for org filter

lib/LocationFilter/LocationFilter.js, lib/MaterialTypeFilter/MaterialTypeFilter.js
=> fix warnings

lib/constants/index.js, lib/constants/item.js, translations/stripes-acq-components/en.json
=> Add inventory item status constant

lib/FormFooter/FormFooter.js, lib/LocationFilter/LocationFilterContainer.js, lib/utils/getLocationOptions.js, lib/utils/index.js
new util fns
While it's helpful for reviewers to help identify potential problems, ensuring …
=> Add get location options util

test/bigtest/interactors/controls/CheckboxInteractor.js, test/bigtest/interactors/controls/index.js
=> add checkbox interactor

test/bigtest/network/configs/memberships.js
=> fix acq membership bigtest mirage response

package.json
=> bump up finance.transaction interface version

lib/hooks/useShowToast.js, lib/utils/showToast.js, package.json
=> use common context from stripes-core

CHANGELOG.md, lib/AcqList/utils/queryUtils.js, lib/AcqList/utils/queryUtils.test.js
https://issues.folio.org/browse/UINV-118 …
=> UINV-118 AcqList buildDateRangeQuery util

lib/hooks/useShowToast.js
=> fix callout in tests

lib/Tags/TagsContainer.js
=> replace context for callout

CHANGELOG.md, lib/AcqCheckboxFilter/AcqCheckboxFilter.test.js, lib/AcqList/hooks/index.js, lib/AcqList/hooks/useLocationReset.js, lib/FieldOrganization/FieldOrganization.js, lib/FieldOrganization/index.js, lib/index.js
https://issues.folio.org/browse/UINV-124 …
=> UINV-124 FieldOrganization component

lib/AcqList/hooks/useFilters.js, lib/AcqList/utils/queryUtils.js
=> leverage code to a new function, reset search index

lib/AcqList/ResultsPane/ResultsPane.js
=> add test attribute

lib/AcqList/SingleSearchForm/SingleSearchForm.js
=> add test id for search

CHANGELOG.md, lib/LocationFilter/LocationFilter.js, lib/LocationFilter/LocationFilterContainer.js
https://issues.folio.org/browse/UIREC-60 …
=> UIREC-60 Improve Location filter on the Titles list to use location look-up

translations/stripes-acq-components/pt_BR.json
=> Update translation strings as of 20200312T133304

CHANGELOG.md, lib/AcqCheckboxFilter/AcqCheckboxFilter.test.js, package.json
=> Release v2.0.1

CHANGELOG.md, lib/FieldLocation/FieldLocationFinal.js, lib/FieldLocation/FieldLocationFinal.test.js, lib/FieldLocation/index.js, lib/index.js, lib/manifests/location.js, test/jest/__mock__/index.js, test/jest/__mock__/stripesLocationLookup.mock.js
https://issues.folio.org/browse/UIREC-59 …
=> UIREC-59 Use only select Location plugin

lib/manifests/location.js
=> UIREC-59 Fix path

lib/hooks/useShowCallout.js
=> pass `timeout` to the callout

lib/Tags/TagsContainer.js
It's not clear what this call of refresh manifest resources for. So it's better to not call it, looks working. I bet it's a copy-paste from stripes-smart-components
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> remove unnecessary refreshRemote

lib/constants/constants.js
Basically, it's a potential weak spot if you have to request more than 1K records in one request. But if you have to - it requires to load records in batch queries (also per 1K records in request).  …
=> change limit per request to 1000 records

lib/AcqList/SingleSearchForm/SingleSearchForm.js
=> fix placeholders for AcqList

CHANGELOG.md, lib/constants/api.js, test/bigtest/network/configs/index.js, test/bigtest/network/configs/orders.js, test/bigtest/network/factories/index.js, test/bigtest/network/factories/order.js, test/bigtest/network/models/index.js, test/bigtest/network/models/order.js, test/bigtest/network/serializers/index.js, test/bigtest/network/serializers/order.js
add common config, model, serializer, factory for order
https://issues.folio.org/browse/UIREC-66 …
=> UIREC-66 Order configs for tests

CHANGELOG.md, lib/ModalFooter/ModalFooter.css, lib/ModalFooter/ModalFooter.js, lib/ModalFooter/ModalFooter.test.js, lib/ModalFooter/index.js, lib/index.js
https://issues.folio.org/browse/UIREC-67 …
=> UIREC-67 Add ModalFooter with right buttons alignment

CHANGELOG.md, lib/constants/countries.js
https://issues.folio.org/browse/UIORGS-155 …
=> UIORGS-155 add country labels map

lib/constants/languages.js
From the comment we figured out that language was never shown as a label, always as a code. 
https://issues.folio.org/browse/UIORGS-155 …
=> UIORGS-155 show language label

lib/utils/batchFetch.js, lib/utils/batchFetch.test.js
we need to pass query params
https://issues.folio.org/browse/UIF-190 …
=> UIF-190 pass query params to extend

CHANGELOG.md, lib/AcqList/ResultsPane/ResultStatusMessage.js, lib/AcqList/ResultsPane/index.js, lib/AcqList/hooks/index.js, lib/AcqList/hooks/useResultStatusMessage.js, lib/AcqList/index.js
=> Add no results message hook

CHANGELOG.md, lib/FundDistribution/FundDistributionFields/FundDistributionFields.js
Accessibility Error: Form elements must have labels
https://issues.folio.org/browse/UINV-127 …
=> UINV-127 Accessibility Error: Form elements must have labels

translations/stripes-acq-components/en_US.json
=> UIOR-516 add transl to en_US

lib/UserFilter/PluggableUserFilter.js
For release we can't display translation keys, so as  a hotfix I suggest to use existing translations …
=> UIOR-516 fix translation for release

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIOR-548 …
=> Release v2.0.4

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/he.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/ja.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/ru.json, translations/stripes-acq-components/ur.json, translations/stripes-acq-components/zh_CN.json, translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20200409T134057

lib/PluginFindRecord/PluginFindRecord.js
=> remove id to avoid non-unique id console warning

CHANGELOG.md, test/bigtest/network/configs/configs.js, test/bigtest/network/configs/index.js, test/bigtest/network/factories/config.js, test/bigtest/network/factories/index.js, test/bigtest/network/models/config.js, test/bigtest/network/models/index.js, test/bigtest/network/serializers/config.js, test/bigtest/network/serializers/index.js
https://issues.folio.org/browse/UINV-123
To have a common config, factory, model, serializer for configs and use in tests across modules …
=> UINV-123 Move config, factory, model, serializer for configs

lib/hooks/useShowCallout.js
=> show error toasts without timeout by default

CHANGELOG.md, lib/AcqList/FiltersPane/FiltersPane.js, lib/AcqList/ResultsPane/FilterPaneToggle.js, lib/AcqList/ResultsPane/ResultsPane.js
Organizations is not using the same Expand/Collapse as implemented in Q4 2019
https://issues.folio.org/browse/UIORGS-151 …
=> UIORGS-151 use common collapse/expand filters buttons

lib/AcqList/NoResultsMessage/NoResultsMessage.js, lib/AcqList/NoResultsMessage/index.js, lib/AcqList/index.js
Leverage common code regarding no result message
https://issues.folio.org/browse/UIORGS-151 …
=> UIORGS-151 leverage no result message

translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20200428T150732

jest.config.js
=> fix no test found for jest on windows

lib/AcqList/ResultsPane/FilterPaneToggle.js
small fix to not count de-selected filters
https://issues.folio.org/browse/UIORGS-151
While …
=> UIORGS-115 fix count of selected filters

CHANGELOG.md, lib/AcqList/hooks/useLocationSorting.js, lib/AcqList/utils/searchUtils.js
This makes possible to turn on default sorting indicator on lists if default sorting param is passed
https://issues.folio.org/browse/UIF-202 …
=> UIF-202 add default sorting param

lib/AcqList/SingleSearchForm/SingleSearchForm.js, lib/CountryFilter/CountryFilter.js, lib/FieldSelect/FieldSelect.js, lib/LanguageFilter/LanguageFilter.js
=> prepare to stripesv4, remove intlShape

translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20200513T135229

translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20200515T182823

CHANGELOG.md, lib/constants/api.js, lib/constants/index.js, lib/constants/piece.js, lib/manifests/index.js, lib/manifests/piece.js, test/bigtest/network/configs/configItems.js, test/bigtest/network/configs/configPieces.js, test/bigtest/network/configs/configRequests.js, test/bigtest/network/configs/index.js, test/bigtest/network/factories/index.js, test/bigtest/network/factories/item.js, test/bigtest/network/factories/piece.js, test/bigtest/network/factories/request.js, test/bigtest/network/models/index.js, test/bigtest/network/models/item.js, test/bigtest/network/models/piece.js, test/bigtest/network/models/request.js, test/bigtest/network/serializers/index.js, test/bigtest/network/serializers/item.js, test/bigtest/network/serializers/piece.js, test/bigtest/network/serializers/request.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIOR-444 …
=> UIOR-444 common constant for Piece, BigTest config

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/he.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/ja.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/ru.json, translations/stripes-acq-components/ur.json, translations/stripes-acq-components/zh_CN.json, translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20200519T123842

CHANGELOG.md, lib/constants/api.js, package.json
https://issues.folio.org/browse/UIORGS-178 …
=> UIORGS-178 Switch to mod-organizations

CHANGELOG.md, lib/PluginFindRecord/PluginFindRecordModal.js
https://issues.folio.org/browse/UIOR-564 …
=> UIOR-564 pass initialFilterState prop to S&SQ

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ru.json
=> Update translation strings as of 20200521T142352

lib/FundDistribution/FundDistributionFields/FundDistributionFields.js, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsContainer.js, lib/PluginFindRecord/PluginFindRecordModal.js, lib/utils/getFundsForSelect.js
To pass fund code to back-end, eventually it's needed there …
=> fill fund code

CHANGELOG.md, lib/AcqUnits/AcqUnitsField/AcqUnitsField.js, lib/AcqUnits/AcqUnitsField/AcqUnitsFieldContainer.js
https://issues.folio.org/browse/UIORGS-78 …
=> UIORGS-78 pass id to AcqUnitField

lib/constants/order.js, package.json
=> leverage common constants

lib/LoadingPane/LoadingPane.js
=> re-use LoadingPane

translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/ru.json
=> Update translation strings as of 20200526T141248

lib/constants/piece.js
=> add misisng piec format option

lib/AcqUnits/AcqUnitsField/AcqUnitsFieldContainer.js
=> UIORGS-78 fix doubled units

lib/AcqList/utils/queryUtils.js
=> add custom sort field names

lib/FieldDatepicker/FieldDatepicker.js, lib/FieldLocation/FieldLocationFinal.js, lib/FieldSelect/FieldSelect.js
* added `isDisabled` prop to FieldLocation;
* fixed ProprType for components;
https://issues.folio.org/browse/UIREC-94 …
=> UIREC-94 isDisabled for FieldLocation

CHANGELOG.md, lib/utils/validateRequired.js, lib/utils/validateRequired.test.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIORGS-177 …
=> UIORGS-177 add validation to not allow spaces

lib/Tags/TagsContainer.js, lib/Tags/TagsPane.js
=> UIOR-567 fix missing callouts

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/he.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/ja.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/ru.json, translations/stripes-acq-components/ur.json, translations/stripes-acq-components/zh_CN.json, translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20200604T202430

CHANGELOG.md, lib/FieldLocation/FieldLocationFinal.js, lib/FieldLocation/FieldLocationFinal.test.js, lib/FieldLocation/FieldLocationFinalContainer.js, lib/FieldLocation/FieldLocationFinalContainer.test.js, lib/FieldLocation/index.js, lib/utils/getLocationOptions.js, package.json
https://issues.folio.org/browse/UIREC-90 …
=> UIREC-90 Update select location workflow for Piece

lib/hooks/useModalToggle.js
fix toggle since it was causing issues (wrong modal opens, etc.)
https://issues.folio.org/browse/UIOR-444 …
=> UIOR-444 submit after piece deletion

lib/utils/acqRowFormatter/acqRowFormatter.js, lib/utils/acqRowFormatter/acqRowFormatter.test.js
=> align to MCL default formatter changes

CHANGELOG.md, lib/Tags/TagsForm.js, package.json
=> Release v2.1.2

translations/stripes-acq-components/zh_CN.json
=> Update translation strings as of 20200615T161518

CHANGELOG.md, lib/AcqList/hooks/index.js, lib/AcqList/hooks/useLocalStorageFilters.js, lib/AcqList/hooks/useLocalStorageFilters.test.js, package.json
https://issues.folio.org/browse/UIOR-417 …
=> UIOR-417 useLocalStorageFilters

CHANGELOG.md, lib/AcqTagsFilter/AcqTagsFilter.js
https://issues.folio.org/browse/UIOR-522 …
=> UIOR-522 fix aria-labelledby attribute value

CHANGELOG.md, lib/SelectionFilter/SelectionFilter.js
Accessibility Error: Buttons must have discernible text
https://issues.folio.org/browse/UIOR-523 …
=> UIOR-523 pass right description and id

CHANGELOG.md, lib/LocationFilter/LocationFilter.js, lib/OrganizationFilter/PluggableOrganizationFilter.js, lib/UserFilter/PluggableUserFilter.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIOR-524 …
=> UIOR-524 Form elements must have labels

lib/Tags/TagsForm.js
=> UIOR-524 pass aria-labelledby to multiselect without label

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/he.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/ja.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/ru.json, translations/stripes-acq-components/ur.json, translations/stripes-acq-components/zh_CN.json, translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20200618T161121

CHANGELOG.md, lib/CountryFilter/CountryFilter.js, lib/LanguageFilter/LanguageFilter.js
https://issues.folio.org/browse/UIORGS-157 …
=> UIORGS-157 Accessibility error: IDs must be unique

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/he.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/ja.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/ru.json, translations/stripes-acq-components/ur.json, translations/stripes-acq-components/zh_CN.json, translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20200623T182030

translations/stripes-acq-components/ru.json
=> Update translation strings as of 20200624T182544

translations/stripes-acq-components/ru.json
=> Update translation strings as of 20200626T180122

translations/stripes-acq-components/ru.json
=> Update translation strings as of 20200701T150841

CHANGELOG.md, lib/PluginFindRecord/PluginFindRecord.js, lib/PluginFindRecord/PluginFindRecordModal.js
https://issues.folio.org/browse/UINV-161
Add validate selected records callback
While it's …
=> UINV-161 Add validate selected records callback

CHANGELOG.md, lib/FieldSelection/FieldSelectionFinal.js, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.js, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinalContainer.js, lib/FundDistribution/index.js, lib/RepeatableFieldWithErrorMessage/RepeatableFieldWithValidation.js, lib/RepeatableFieldWithErrorMessage/index.js, lib/utils/index.js, lib/utils/validateFundDistributionFinal.js, package.json
https://issues.folio.org/browse/UIOR-561 …
=> UIOR-561 final form changes

lib/CurrencySymbol/CurrencySymbol.js, lib/FieldSelection/FieldSelectionFinal.js, lib/utils/calculateFundDistributionTotal.js
- display currency symbol without error;
- don't fail on fund distribution calculation if no currency is provided;
- Selection parse empty value as undefined to not send empty string to back-end
https://issues.folio.org/browse/UIOR-561 …
=> UIOR-561 more final form fixes

CHANGELOG.md, lib/AcqCheckboxFilter/AcqCheckboxFilter.test.js, package.json
to fetch freshest stripes-components with currency options hook we have to upgrade to stripes v5 …
=> UISACQCOMP-2 CurrencySelect values are not translated

CHANGELOG.md, lib/AcqUnits/AcqUnitsField/AcqUnitsField.js
https://issues.folio.org/browse/UIORGS-164 …
=> UIORGS-164 pass id of label

translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/zh_CN.json
=> Update translation strings as of 20200721T202356

CHANGELOG.md, jest.config.js, jest.setup.js, lib/AcqCheckboxFilter/AcqCheckboxFilter.js, lib/AcqDateRangeFilter/AcqDateRangeFilter.js, lib/AcqDateRangeFilter/AcqDateRangeFilter.test.js, lib/AcqTagsFilter/AcqTagsFilter.js, lib/CountryFilter/CountryFilter.js, lib/CountryFilter/CountryFilter.test.js, lib/FilterAccordion/FilterAccordion.js, lib/FilterAccordion/index.js, lib/LanguageFilter/LanguageFilter.js, lib/LanguageFilter/LanguageFilter.test.js, lib/OrganizationFilter/PluggableOrganizationFilter.js, lib/SelectionFilter/SelectionFilter.js, lib/utils/createOnChangeSelectionFilter.js, lib/utils/index.js, package.json
Improvement to respect `disabled` prop 
https://issues.folio.org/browse/UIOR-586
While it's …
=> UIOR-586 disable filters while loading

lib/AcqList/NoResultsMessage/NoResultsMessage.js, lib/AcqList/ResultsPane/FilterPaneToggle.js, lib/AcqList/ResultsPane/ResultsPane.js, lib/AcqList/SingleSearchForm/SingleSearchForm.js, lib/AcqList/hooks/index.js, lib/AcqList/hooks/useList.js, lib/AcqList/utils/queryUtils.js
`useList` hook contains common logic for fetching list pages
https://issues.folio.org/browse/UIOR-586 …
=> UIOR-586 useList hook with common code for lists

translations/stripes-acq-components/ru.json
=> Update translation strings as of 20200727T130814

CHANGELOG.md, lib/AcqEndOfList/AcqEndOfList.css, lib/AcqEndOfList/AcqEndOfList.js, lib/AcqEndOfList/index.js, lib/index.js
=> AcqEndOfList

CHANGELOG.md, lib/AmountWithCurrencyField/AmountWithCurrencyField.js
add `showBrackets` prop in `<AmountWithCurrencyField />` to show amount in brackets for negative values
https://issues.folio.org/browse/UIF-215
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
=> UIF-215 Add showBrackets prop

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/he.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/ja.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/ru.json, translations/stripes-acq-components/ur.json, translations/stripes-acq-components/zh_CN.json, translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20200811T193833

CHANGELOG.md, lib/constants/order.js, lib/manifests/index.js, lib/manifests/orders.js
to use common code for payment status and order lines api
https://issues.folio.org/browse/UINV-173 …
=> UINV-173 common constant and resource

CHANGELOG.md, lib/AcqList/utils/queryUtils.js
https://issues.folio.org/browse/UIORGS-197 …
=> UIORGS-197 customize column names for sorting

test/bigtest/interactors/CalloutInteractor.js, test/bigtest/interactors/index.js
=> UINV-83 leverage CalloutInteractor

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/he.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/ja.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/ru.json, translations/stripes-acq-components/ur.json, translations/stripes-acq-components/zh_CN.json, translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20200820T141724

translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/zh_CN.json
=> Update translation strings as of 20200824T140725

lib/PluginFindRecord/PluginFindRecordModal.js
=> fix layout

lib/PluginFindRecord/PluginFindRecordModal.js
https://issues.folio.org/browse/UINV-161 …
=> UINV-161 fix missing confirmation modal

translations/stripes-acq-components/zh_CN.json
=> Update translation strings as of 20200827T215834

CHANGELOG.md, lib/Notes/AcqNoteCreatePage.js, lib/Notes/AcqNoteEditPage.js, lib/Notes/AcqNoteViewPage.js, lib/Notes/index.js, lib/Notes/util.js, lib/index.js
https://issues.folio.org/browse/UIORGS-184 …
=> UIORGS-184 leverage common note route components

CHANGELOG.md, lib/FrontendSortingMCL/FrontendSortingMCL.js, lib/FrontendSortingMCL/index.js, lib/index.js
usually we need to show sorted records in MCL, so I've leveraged common code to a component.
* required prop of sorted field;
* could include arrow as last column;
* show end of list marker;
https://issues.folio.org/browse/UINV-178 …
=> UINV-178 Leverage code for client-side sorting

CHANGELOG.md, lib/FieldDatepicker/FieldDatepicker.js
https://issues.folio.org/browse/UINV-181 …
=> UINV-181 fix `Datepicker` for redux-form

lib/AmountWithCurrencyField/AmountWithCurrencyField.js, package.json, test/jest/__mock__/stripesCore.mock.js, test/jest/__mock__/stripesSmartComponents.mock.js
=> bump up test libs

CHANGELOG.md, lib/AcqList/SingleSearchForm/SingleSearchForm.js, lib/AcqUnits/AcqUnitsView/AcqUnitsView.js, lib/AcqUnits/AcqUnitsView/AcqUnitsView.test.js, lib/PluginFindRecord/PluginFindRecordModal.js, lib/hooks/useAccordionToggle/useAccordionToggle.test.js, package.json, test/jest/__mock__/stripesCore.mock.js, test/jest/__mock__/stripesSmartComponents.mock.js
* display <NoValue /> if no units selected;
* fix console warning on AcqList search input;
* 
https://issues.folio.org/browse/UIORGS-201 …
=> UIORGS-201 Update view pane to display null as hyphen

CHANGELOG.md, lib/AcqCheckboxFilter/AcqCheckboxFilter.test.js, lib/AcqDateRangeFilter/AcqDateRangeFilter.test.js, lib/AcqUnitFilter/AcqUnitFilter.test.js, lib/AcqUnits/AcqUnitsView/AcqUnitsView.test.js, lib/CountryFilter/CountryFilter.test.js, lib/FieldLocation/FieldLocationFinal.test.js, lib/FieldLocation/FieldLocationFinalContainer.test.js, lib/LanguageFilter/LanguageFilter.test.js, lib/ModalFooter/ModalFooter.test.js, lib/Organization/OrganizationValue/OrganizationValueContainer.test.js, lib/OrganizationFilter/PluggableOrganizationFilter.test.js, lib/TextFilter/TextFilter.js, lib/TextFilter/index.js, lib/UserFilter/PluggableUserFilter.test.js, lib/index.js, test/jest/__mock__/index.js, test/jest/__mock__/reactIntl.mock.js
https://issues.folio.org/browse/UICIRCLOG-17 …
=> UICIRCLOG-17 react-intl mock

CHANGELOG.md, lib/FieldSelect/FieldSelect.js, lib/FieldSelect/FieldSelectFinal.js
display fiscal year select disabled as KeyValue with selected year
https://issues.folio.org/browse/UIF-251 …
=> UIF-251 Display disabled FieldSelect as KeyValue

test/bigtest/network/factories/vendor.js
=> fix test of fake vendor name

lib/FieldSelection/FieldSelectionFinal.js, lib/FolioFormattedTime/FolioFormattedTime.js
* display NoValue in case no value for FormattedTime is provided
* display KeyValue for FieldSelection
https://issues.folio.org/browse/UIOR-607
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
=> UIOR-607 dispaly time and selection in non-interactive

CHANGELOG.md, jest.config.js, lib/FieldDatepicker/FieldDatepicker.js, lib/FieldLocation/FieldLocationFinal.js, lib/FieldSelect/FieldSelect.js, lib/FieldSelect/FieldSelectFinal.js, lib/FieldSelection/FieldSelection.js, lib/FieldSelection/FieldSelectionFinal.js, lib/Fields/AcqDatepicker.js, lib/Fields/AcqSelect.js, lib/Fields/AcqSelection.js, lib/Fields/AcqTextArea.js, lib/Fields/AcqTextField.js, lib/Fields/index.js, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.js, lib/FundDistribution/FundDistributionView/FundDistributionView.js, lib/index.js
https://issues.folio.org/browse/UIOR-607 …
=> UIOR-607 wrappers for common controls with non-interactive

lib/Fields/AcqSelect.js
https://issues.folio.org/browse/UIOR-607 …
=> UIOR-607 display prefix and suffix as NoValue if not selected

test/jest/__mock__/stripesCore.mock.js
=> useStripes mock

CHANGELOG.md, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.js, lib/FundDistribution/FundDistributionView/FundDistributionView.js, lib/utils/validateFundDistributionFinal.js, translations/stripes-acq-components/en.json
* moved validation function inside common component (it's the same for orders and invoices);
* fixed view to display NoValue,
https://issues.folio.org/browse/UIF-253
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> UIF-253 Allow user to use multiple expense class from same fund

translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/he.json, translations/stripes-acq-components/hi_IN.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/ja.json, translations/stripes-acq-components/ko.json, translations/stripes-acq-components/pl.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/ru.json, translations/stripes-acq-components/ur.json, translations/stripes-acq-components/zh_CN.json, translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20200928T202231

translations/stripes-acq-components/fr_FR.json
=> Update translation strings as of 20201005T202004

lib/constants/index.js, lib/constants/transaction.js
=> Leverage transaction types

CHANGELOG.md, jest.config.js
=> separate coverage die for Jest

CHANGELOG.md, lib/FieldTags/FieldTagsContainer.js, lib/FieldTags/FieldTagsFinal.js, package.json
=> fix tags with caps

lib/utils/acqRowFormatter/acqRowFormatter.css
=> fix aligning of last column with arrow or button

CHANGELOG.md, package.json
https://issues.folio.org/browse/UISACQCOMP-4 …
=> UISACQCOMP-4

translations/stripes-acq-components/it_IT.json
=> Update translation strings as of 20201013T203429

CHANGELOG.md, lib/AcqList/utils/queryUtils.js
https://issues.folio.org/browse/UIREC-101 …
=> UIREC-101 Filtering not working on Receiving

CHANGELOG.md, lib/AcqList/ResultsPane/ResultsPane.js, lib/AcqList/hooks/useList.js
return ref for results pane header and focus it if data response has come
https://issues.folio.org/browse/UIORGS-208 …
=> UIORGS-208 focus results pane

CHANGELOG.md, lib/PluginFindRecord/PluginFindRecordModal.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIPFINT-14
https://issues.folio.org/browse/UIPFCONT-11
While …
=> UIPFINT-14 Add aria-label to select item checkbox

CHANGELOG.md, lib/FieldAutoSuggest/FieldAutoSuggest.js, lib/FieldAutoSuggest/FieldAutoSuggestFinal.js, lib/FieldAutoSuggest/index.js
https://issues.folio.org/browse/UIORGS-200 …
=> UIORGS-200 Migrate to React-final-form

CHANGELOG.md, lib/AcqCheckboxFilter/AcqCheckboxFilter.js
https://issues.folio.org/browse/UISACQCOMP-7 …
=> UISACQCOMP-7 fix staying focus

translations/stripes-acq-components/ja.json
=> Update translation strings as of 20201102T140138

CHANGELOG.md, lib/AcqDateRangeFilter/AcqDateRangeFilter.js
Invoice date filters are off set by timezone somehow.
Earlier it was a fix for common component, but it looks like we can remove this.
https://issues.folio.org/browse/UINV-202
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
=> UINV-202 fix date range filter

lib/utils/validateURL/validateURL.js
https://issues.folio.org/browse/UIORGS-200 …
=> UIORGS-200 validateURLRequired

translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/ja.json
=> Update translation strings as of 20201105T151643

CHANGELOG.md, package.json
https://issues.folio.org/browse/UISACQCOMP-8 …
=> Release v2.2.2

CHANGELOG.md, lib/utils/batchFetch.js
https://issues.folio.org/browse/UISACQCOMP-10 …
=> UISACQCOMP-10 add filter param name argument to batchFetch

CHANGELOG.md, package.json
https://issues.folio.org/browse/UISACQCOMP-11 …
=> Release v2.2.3

jest.config.js
=> ignore bigtest and nightmare for Jest

translations/stripes-acq-components/ar.json, translations/stripes-acq-components/ber.json, translations/stripes-acq-components/ca.json, translations/stripes-acq-components/da.json, translations/stripes-acq-components/de.json, translations/stripes-acq-components/en_GB.json, translations/stripes-acq-components/en_SE.json, translations/stripes-acq-components/en_US.json, translations/stripes-acq-components/es.json, translations/stripes-acq-components/es_419.json, translations/stripes-acq-components/es_ES.json, translations/stripes-acq-components/fr.json, translations/stripes-acq-components/fr_FR.json, translations/stripes-acq-components/he.json, translations/stripes-acq-components/hi_IN.json, translations/stripes-acq-components/hu.json, translations/stripes-acq-components/it_IT.json, translations/stripes-acq-components/ja.json, translations/stripes-acq-components/ko.json, translations/stripes-acq-components/pl.json, translations/stripes-acq-components/pt_BR.json, translations/stripes-acq-components/pt_PT.json, translations/stripes-acq-components/ru.json, translations/stripes-acq-components/ur.json, translations/stripes-acq-components/zh_CN.json, translations/stripes-acq-components/zh_TW.json
=> Update translation strings as of 20201124T212804

CHANGELOG.md, lib/AcqList/ResultsPane/ResultsPane.js
https://issues.folio.org/browse/UIOR-631 …
=> UIOR-631 Add Action menu

CHANGELOG.md, lib/TextFilter/TextFilter.js
UICIRCLOG-28 Clicking Circulation log app should move focus to first field.
Need to pass `autoFocus` prop to the `<TextField>`
Propagate all the `...props` to the inner `<TextField>`.
The propTypes of TextField are added to the component propTypes.
Explicit `type` and `disabled` props are removed as they are now the part of `...props`. 
Ideally all of the …
=> UICIRCLOG-28 Propagate ...props in TextFilter to TextField

test/jest/__mock__/stripesCore.mock.js
=> mock IfPermission component

CHANGELOG.md, test/jest/setupTests.js
See https://github.com/facebook/jest/issues/335#issuecomment-703691592 …
=> UICIRCLOG-34 Make global __mocks__ be used in submodules

lib/AcqCheckboxFilter/AcqCheckboxFilter.test.js, lib/AcqDateRangeFilter/AcqDateRangeFilter.test.js, lib/AcqList/hooks/useLocalStorageFilters.test.js, lib/AcqUnitFilter/AcqUnitFilter.test.js, lib/AcqUnits/AcqUnitsView/AcqUnitsView.test.js, lib/CountryFilter/CountryFilter.test.js, lib/FieldLocation/FieldLocationFinal.test.js, lib/FieldLocation/FieldLocationFinalContainer.test.js, lib/LanguageFilter/LanguageFilter.test.js, lib/ModalFooter/ModalFooter.test.js, lib/Organization/OrganizationValue/OrganizationValueContainer.test.js, lib/OrganizationFilter/PluggableOrganizationFilter.test.js, lib/PermissionedRoute/PermissionedRoute.test.js, lib/UserFilter/PluggableUserFilter.test.js
follow-up to https://github.com/folio-org/stripes-acq-components/pull/390 …
=> UICIRCLOG-34 remove redundant __mock__ imports

CHANGELOG.md, PERSONAL_DATA_DISCLOSURE.md
https://issues.folio.org/browse/UISACQCOMP-13 …
=> UISACQCOMP-13 Add personal data disclosure form

CHANGELOG.md, lib/AcqList/utils/queryUtils.js
UICIRCLOG-33 Refine `Renewed` filter results
-  Given Circulation log
- When I select the `Renewed` filter
- Then items that have renewed appear, but NOT items that have renewed through override, since there is a separate filter for that
change CQL query = to == 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
=> UICIRCLOG-33 change CQL query = to ==

test/jest/babel.config.js
https://issues.folio.org/browse/UIF-237 …
=> fix babel config

CHANGELOG.md, lib/FieldSelect/FieldSelectFinal.js
fix validation re-run on fields with dynamic `required` prop
https://issues.folio.org/browse/UIF-274
added key prop as suggested in docs
https://final-form.org/docs/react-final-form/types/FieldProps#validate …
=> UIF-274 fix all select lists with dynamic required prop

CHANGELOG.md, lib/AcqDateRangeFilter/AcqDateRangeFilter.js, lib/AcqDateRangeFilter/AcqDateRangeFilter.test.js
https://issues.folio.org/browse/UICIRCLOG-35 …
=> UISACQCOMP-15 Reformat dates to match date format across FOLIO

lib/FieldSelect/FieldSelectFinal.js
https://issues.folio.org/browse/UIF-274 …
=> UIF-274 support custom keys

lib/Tags/TagsBadge/TagsBadge.js
=> fix console warning

CHANGELOG.md, lib/FieldOrganization/FieldOrganization.js
=> UINV-169 call change org on clear field

jest.config.js, lib/OrganizationFilter/PluggableOrganizationFilter.js, package.json, test/bigtest/helpers/turn-off-warnings.js
=> fix jest test running and console warnings

lib/utils/fetchAllRecords.js, lib/utils/index.js
common function to load all records in batches by 1000 records
https://issues.folio.org/browse/UIF-238 …
=> UIF-238 fetch all records fn

CHANGELOG.md, package.json
=> bump stripes v6

CHANGELOG.md, lib/PluginFindRecord/PluginFindRecordModal.js
https://issues.folio.org/browse/UISACQCOMP-9 …
=> UISACQCOMP-9 add aria-label to search field

lib/PluginFindRecord/PluginFindRecordModal.js
https://issues.folio.org/browse/UISACQCOMP-9 …
=> UISACQCOMP-9 new modal ariaLabel prop

CHANGELOG.md, lib/FolioFormattedDate/FolioFormattedDate.js, lib/FolioFormattedTime/FolioFormattedTime.js, lib/utils/formatDate.js, lib/utils/formatDateTime.js, lib/utils/index.js
Update format date and format time …
=> UIOR-645 Update format date and format time

lib/AcqList/utils/queryUtils.js, lib/SelectionFilter/SelectionFilter.js
to fix array field filtering we need a separate query transformer
link to initial PR https://github.com/folio-org/stripes-acq-components/pull/394
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
=> UICIRCLOG-33 add array filtering fix

lib/FolioFormattedDate/FolioFormattedDate.js, lib/utils/formatDate.js
it was an error to change behavior for all places, and no requirements …
=> revert some date fromat code

lib/constants/transaction.js
add new constant for Rollover transfer
https://issues.folio.org/browse/UIF-282
While it's …
=> UIF-282 add constant for Rollover transaction

CHANGELOG.md, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.js, lib/FundDistribution/FundDistributionView/FundDistributionView.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIOR-618 …
=> UIOR-618 show unavailable fund name

lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.js
=> UIOR-618 fix list of funds

lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.js
=> UIOR-618 fix list of funds (#422)

CHANGELOG.md, lib/Currency/CurrencyValue/CurrencyValue.js, lib/Currency/CurrencyValue/index.js, lib/Currency/FieldCurrency/FieldCurrency.js, lib/Currency/FieldCurrency/index.js, lib/Currency/index.js, lib/CurrencyExchangeRateFields/CurrencyExchangeRateFields.js, lib/CurrencyExchangeRateFields/CurrentExchangeRate/CurrentExchangeRate.js, lib/CurrencyExchangeRateFields/CurrentExchangeRate/CurrentExchangeRate.test.js, lib/CurrencyExchangeRateFields/CurrentExchangeRate/index.js, lib/CurrencyExchangeRateFields/index.js, lib/constants/api.js, lib/index.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIOR-610
- Move code with Currency exchange rate logic from `invoices` to `stripes-acq-components`  …
=> UIOR-610 Set exchange rate manually for POL

lib/CurrencyExchangeRateFields/CurrencyExchangeRateFields.js
=> UIOR610 - fix get filled currency

lib/CurrencyExchangeRateFields/CurrencyExchangeRateFields.js
=> add prop to CurrencyExchangeRateFields

CHANGELOG.md, Jenkinsfile, lib/AcqDateRangeFilter/AcqDateRangeFilter.js, lib/AcqDateRangeFilter/AcqDateRangeFilter.test.js, lib/FieldDatepicker/FieldDatepicker.js, lib/FolioFormattedDate/FolioFormattedDate.js, lib/hooks/index.js, lib/hooks/useLocaleDateFormat.js, lib/utils/formatDate.js, test/jest/__mock__/reactIntl.mock.js
Reformat dates to match date format across FOLIO (based on selected locale)
https://issues.folio.org/browse/UISACQCOMP-16 …
=> UISACQCOMP-16 use FOLIO timezone to display dates

lib/AcqList/utils/queryUtils.test.js, lib/CurrencyExchangeRateFields/CurrentExchangeRate/CurrentExchangeRate.test.js
=> Fix tests console warnings

CHANGELOG.md, lib/utils/validateRequired.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIF-280 …
=> UIF-280 add positive number validation

lib/constants/api.js, lib/constants/order.js, lib/manifests/orders.js
=> leverage common order constants

package.json, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIF-280 …
=> UIF-280 Update en.json

CHANGELOG.md, lib/CurrencyExchangeRateFields/CurrentExchangeRate/CurrentExchangeRate.js, lib/VendorReferenceNumbers/VendorReferenceNumbersDetails/VendorReferenceNumbersDetails.js, lib/VendorReferenceNumbers/VendorReferenceNumbersDetails/index.js, lib/VendorReferenceNumbers/VendorReferenceNumbersFields/VendorReferenceNumbersFields.js, lib/VendorReferenceNumbers/VendorReferenceNumbersFields/index.js, lib/VendorReferenceNumbers/VendorReferenceNumbersFields/utils.js, lib/VendorReferenceNumbers/index.js, lib/constants/index.js, lib/constants/refNumberType.js, lib/index.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIOR-519 …
=> UIOR-519 Vendor ref number and type are repeatable

lib/apiHooks/funds.js, lib/apiHooks/index.js, lib/index.js, lib/utils/fetchAllRecords.js, package.json
to load all funds and cache it …
=> UIF-284 add all funds react-query hook

lib/FieldTags/FieldTagsContainer.js, lib/FieldTags/FieldTagsFinal.js, test/jest/__mock__/currencyData.mock.js
=> improvements to unit tests

test/jest/__mock__/stripesCore.mock.js
=> UIPBEX-2 mock useOkapiKy

translations/stripes-acq-components/en.json
=> UIOR-519 Fix label

lib/constants/api.js
https://issues.folio.org/browse/UIF-283 …
=> UIF-283 Add Invoices API constant

CHANGELOG.md, lib/ExchangeRateValue/ExchangeRateValue.js, lib/ExchangeRateValue/ExchangeRateValue.test.js, lib/ExchangeRateValue/index.js, lib/ExchangeRateValue/useExchangeRateValue.js, lib/ExchangeRateValue/useExchangeRateValue.test.js, lib/index.js, package.json, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UINV-222 …
=> UINV-222 Add Extended Info accordion to Invoice

lib/AcqEndOfList/AcqEndOfList.test.js, lib/AcqTagsFilter/AcqTagsFilter.test.js, lib/AmountWithCurrencyField/AmountWithCurrencyField.test.js, lib/BooleanFilter/BooleanFilter.test.js, package.json
https://issues.folio.org/browse/FAT-47 …
=> FAT-47 some unit tests [WIP]

CHANGELOG.md, lib/FieldDatepicker/FieldDatepicker.js, test/bigtest/interactors/controls/SelectInteractor.js, test/bigtest/interactors/controls/TextFieldInteractor.js
Do not pass `onBlur` prop to `Field` from react-final-form …
=> UIF-289 Fix onBlur prop for FieldDatepicker

lib/FundDistribution/FundDistributionView/FundDistributionView.test.js, lib/FundDistribution/FundDistributionView/FundDistributionViewContainer.test.js, lib/PluginFindRecord/PluginFindRecord.test.js, lib/Tags/TagsBadge/TagsBadge.test.js, lib/Tags/TagsBadge/TagsBadgeContainer.test.js, lib/Tags/TagsContainer.test.js, lib/Tags/TagsPane.test.js, lib/utils/batchFetch.js, test/jest/helpers/mockOffsetSize.js
https://issues.folio.org/browse/FAT-47 …
=> FAT-47 more tests 2

lib/CurrencyExchangeRateFields/CurrencyExchangeRateFields.js, lib/CurrencyExchangeRateFields/CurrencyExchangeRateFields.test.js, lib/MaterialTypeFilter/MaterialTypeFilterContainer.test.js, lib/ProductIdDetails/ProductIdDetails.test.js, lib/ProductIdDetails/ProductIdDetailsContainer.test.js, lib/TextFilter/TextFilter.test.js, lib/TypeToggle/TypeToggle.test.js, lib/VendorReferenceNumbers/VendorReferenceNumbersDetails/VendorReferenceNumbersDetails.test.js, test/jest/__mock__/currencyData.mock.js
https://issues.folio.org/browse/FAT-47 …
=> FAT-47 more tests 4

lib/AcqList/FiltersPane/FiltersPane.test.js, lib/AcqList/ResetButton/ResetButton.js, lib/AcqList/ResetButton/ResetButton.test.js, lib/AcqList/ResultsPane/ResultsPane.js, lib/AcqList/ResultsPane/ResultsPane.test.js, lib/AcqList/SingleSearchForm/SingleSearchForm.js, lib/AcqList/SingleSearchForm/SingleSearchForm.test.js, lib/AcqList/utils/searchUtils.test.js, package.json
https://issues.folio.org/browse/FAT-47 …
=> FAT-47 more unit tests

CHANGELOG.md, README.md, package.json
https://issues.folio.org/browse/UISACQCOMP-12 …
=> Release v2.3.0

lib/FundDistribution/FundDistributionFields/calculateAmountsAndTotal.js, lib/FundDistribution/FundDistributionFields/calculateAmountsAndTotal.test.js, lib/FundDistribution/FundDistributionView/FundDistributionView.js, lib/FundDistribution/FundDistributionView/FundDistributionView.test.js, lib/FundDistribution/FundDistributionView/FundDistributionViewContainer.js
on the back-end side it was implemented slightly different - add penny to the last records and remove pennies starting from first.
also displaying amounts should use the same code to be consistent
https://issues.folio.org/browse/UISACQCOMP-17 …
=> UISACQCOMP-17 sync with back-end

CHANGELOG.md, lib/FileUploader/FileUploader.js
https://issues.folio.org/browse/UISACQCOMP-22 …
=> UISACQCOMP-22 Attaching file to invoice doesn't work properly when user clicks Choose file

lib/hooks/useShowCallout/useShowCallout.js, package.json, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UISACQCOMP-25 …
=> UISACQCOMP-25 start work for precompiled

CHANGELOG.md, lib/AcqList/FiltersPane/FiltersPane.js, lib/AcqList/ResultsPane/ResultsPane.js, lib/AcqList/hooks/index.js, lib/AcqList/hooks/useFiltersToogle/index.js, lib/AcqList/hooks/useFiltersToogle/useFiltersToogle.js, lib/AcqList/hooks/useFiltersToogle/useFiltersToogle.test.js, lib/hooks/useModalToggle/useModalToggle.test.js, lib/hooks/useToggle/useToggle.test.js
https://issues.folio.org/browse/UISACQCOMP-24 …
=> UISACQCOMP-24 Resizable Panes

lib/KeyValueInline/KeyValueInline.css, lib/KeyValueInline/KeyValueInline.js, lib/KeyValueInline/KeyValueInline.test.js, lib/KeyValueInline/index.js, lib/index.js
https://issues.folio.org/browse/UISACQCOMP-26 …
=> UISACQCOMP-26 KeyValueInline

Jenkinsfile
https://issues.folio.org/browse/UISACQCOMP-25 …
=> UISACQCOMP-25 fix jenkins

lib/AcqUnits/hooks/useAcqRestrictions/useAcqRestrictions.js, lib/AcqUnits/hooks/useAcqRestrictions/useAcqRestrictions.test.js
https://issues.folio.org/browse/UISACQCOMP-27 …
=> UISACQCOMP-27 rename useAcqRestrictions props

lib/AcqList/hooks/useFiltersToogle/useFiltersToogle.test.js, lib/AcqList/hooks/useLocalStorageFilters.test.js, lib/FormFooter/FormFooter.js, test/jest/__mock__/index.js, test/jest/__mock__/localStorage.mock.js
https://issues.folio.org/browse/UISACQCOMP-28 …
=> UISACQCOMP-28 Fix onCancel prop for FormFooter

CHANGELOG.md, package.json
https://issues.folio.org/browse/UISACQCOMP-29 …
=> UISACQCOMP-29 Release v2.3.3

package.json
=> lock broken dep

CHANGELOG.md, lib/utils/batchFetch.js
https://issues.folio.org/browse/UISACQCOMP-30 …
=> UISACQCOMP-30 support batchFetch in react-query

jest.config.js, test/jest/__mock__/stripesConfig.mock.js, test/jest/babel.config.js
https://issues.folio.org/browse/UISACQCOMP-31
* add ["@babel/plugin-proposal-private-methods", \{ "loose": true }] to Babel plugins (due to Babel's warning)
* adjust mocking Ky (see https://github.com/sindresorhus/ky/issues/170 and https://github.com/sindresorhus/ky/issues/340)
* add TS transformation
Ideally all of the PRs involved in breaking changes …
=> UISACQCOMP-31 Update jest-related configs

test/jest/__mock__/stripesCore.mock.js
=> Mock stripes-core useNamespace

test/jest/__mock__/documentCreateRange.mock.js
=> FAT-40 createRange mock

CHANGELOG.md, lib/FundDistribution/FundDistributionFields/fetchExpenseClasses.js
https://issues.folio.org/browse/UISACQCOMP-33 …
=> UISACQCOMP-33 Expense classes are not in alpha order

CHANGELOG.md, lib/AcqUnits/AcqUnitsField/AcqUnitsField.js, lib/AcqUnits/AcqUnitsField/AcqUnitsField.test.js
https://issues.folio.org/browse/UISACQCOMP-34 …
=> UISACQCOMP-34 Search error in acquisition unit component on PO

CHANGELOG.md, lib/PluginFindRecord/PluginFindRecord.js, lib/PluginFindRecord/PluginFindRecord.test.js
https://issues.folio.org/browse/UISACQCOMP-35 …
=> UISACQCOMP-35 Support trigerless mode for lookup plugins

CHANGELOG.md, lib/utils/validateRequired.js, lib/utils/validateRequired.test.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UISACQCOMP-36 …
=> UISACQCOMP-36 validateRequiredPositiveAmount

CHANGELOG.md, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinalContainer.js
https://issues.folio.org/browse/UISACQCOMP-39 …
=> UISACQCOMP-39 Expense class from order template not applied to POL

CHANGELOG.md, lib/FieldHolding/FieldHolding.js, lib/FieldHolding/FieldHolding.test.js, lib/FieldHolding/FieldHoldingLocation.js, lib/FieldHolding/FieldHoldingLocation.test.js, lib/FieldHolding/index.js, lib/FieldHolding/useHoldings.js, lib/FieldHolding/useHoldings.test.js, lib/FieldHolding/utils.js, lib/FieldInventory/FieldInventory.js, lib/FieldInventory/index.js, lib/index.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UISACQCOMP-40 …
=> UISACQCOMP-40 Component to handle holdings and locations

lib/FieldInventory/FieldInventory.js, lib/FieldInventory/FieldInventory.test.js
https://issues.folio.org/browse/UISACQCOMP-40 …
=> UISACQCOMP-40 FieldInventory label less mode

CHANGELOG.md, lib/FundDistribution/FundDistributionView/FundDistributionViewContainer.js, lib/FundDistribution/FundDistributionView/calculateAdjustmentAmounts.js, lib/FundDistribution/FundDistributionView/calculateAdjustmentAmounts.test.js
https://issues.folio.org/browse/UISACQCOMP-41 …
=> UISACQCOMP-41 Invoice FundDistr not showing amount

CHANGELOG.md, lib/utils/generateQueryTemplate.js
https://issues.folio.org/browse/UISACQCOMP-42 …
=> UISACQCOMP-42 Fix search

CHANGELOG.md, package.json
=> Release v2.4.3

CHANGELOG.md, lib/constants/api.js, lib/manifests/piece.js, test/bigtest/network/configs/configPieces.js
https://issues.folio.org/browse/UISACQCOMP-46 …
=> UISACQCOMP-46 Use mod-orders for piece queries

lib/AcqDateRangeFilter/AcqDateRangeFilter.js
https://issues.folio.org/browse/UISACQCOMP-48 …
=> UISACQCOMP-48 Propagate `...rest` props to DateRangeFilter

CHANGELOG.md, lib/FieldHolding/utils.test.js, lib/hooks/index.js, lib/hooks/useLineHoldings/index.js, lib/hooks/useLineHoldings/useLineHoldings.js, lib/hooks/useLineHoldings/useLineHoldings.test.js
https://issues.folio.org/browse/UISACQCOMP-53
Move code for `useLineHoldings` from Orders for common usage …
=> UISACQCOMP-53 Display line locations on piece form

CHANGELOG.md, lib/AcqList/hooks/index.js, lib/AcqList/hooks/useItemToView.js, lib/AcqList/hooks/useItemToView.test.js
https://issues.folio.org/browse/UISACQCOMP-54 …
=> UISACQCOMP-54 Ability to use scroll position of item

CHANGELOG.md, lib/AcqList/PrevNextPagination/PrevNextPagination.css, lib/AcqList/PrevNextPagination/PrevNextPagination.js, lib/AcqList/PrevNextPagination/index.js, lib/AcqList/ResultsPane/ResultsPane.js, lib/AcqList/constants.js, lib/AcqList/hooks/index.js, lib/AcqList/hooks/usePagination/index.js, lib/AcqList/hooks/usePagination/usePagination.js, lib/AcqList/index.js, lib/AcqList/utils/index.js, lib/AcqList/utils/paginationUtils.js, lib/AcqList/utils/queryUtils.js, lib/AcqList/utils/searchUtils.js, package.json
https://issues.folio.org/browse/UISACQCOMP-55
Cover by tests …
=> UISACQCOMP-55 Implement MCL Next/Previous pagination

lib/AcqList/PrevNextPagination/PrevNextPagination.js
https://issues.folio.org/browse/UISACQCOMP-55 …
=>  UISACQCOMP-55 disable Pagination Next button when last item is loaded

lib/AcqList/PrevNextPagination/PrevNextPagination.js, lib/AcqList/PrevNextPagination/PrevNextPagination.test.js, lib/AcqList/hooks/usePagination/usePagination.test.js, lib/AcqList/utils/paginationUtils.test.js, lib/AcqList/utils/searchUtils.test.js
https://issues.folio.org/browse/UISACQCOMP-55
tests for https://github.com/folio-org/stripes-acq-components/pull/535 …
=> UISACQCOMP-55 tests for MCL pagination

lib/constants/constants.js
=> UISACQCOMP-55 const

CHANGELOG.md, lib/AcqUnitFilter/AcqUnitFilterContainer.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UISACQCOMP-56 …
=> UISACQCOMP-56 Add default label for 'Acquisition unit' filter

CHANGELOG.md, lib/utils/validateRequired.js, lib/utils/validateRequired.test.js
https://issues.folio.org/browse/UISACQCOMP-57 …
=> UISACQCOMP-57 Can no longer create POL with Price of 0

lib/FieldHolding/FieldHolding.js
https://issues.folio.org/browse/UISACQCOMP-59
fix invalid reference option for receiving piece list …
=> UISACQCOMP-59 fix invalidReference

CHANGELOG.md, lib/FieldHolding/FieldHolding.js, lib/FieldHolding/FieldHoldingLocation.js, lib/FieldHolding/FieldHoldingLocation.test.js
https://issues.folio.org/browse/UISACQCOMP-64 …
=> UISACQCOMP-64 Use final-form 'Field' component in 'FieldHoldingLocation'

CHANGELOG.md, lib/FieldHolding/FieldHolding.js
https://issues.folio.org/browse/UISACQCOMP-65 …
=> UISACQCOMP-65 POL Title selection overwriting Order template location

lib/hooks/index.js, lib/hooks/useAcqMethodsOptions/index.js, lib/hooks/useAcqMethodsOptions/useAcqMethodsOptions.js, lib/hooks/useAcqMethodsOptions/useAcqMethodsOptions.test.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UISACQCOMP-62 …
=> UISACQCOMP-62 Add resources to interact with Acquisition methods API

CHANGELOG.md, lib/manifests/orders.js
https://issues.folio.org/browse/UISACQCOMP-66 …
=> UISACQCOMP-66 Rename collection field name for Acquisition method

CHANGELOG.md, package.json
https://issues.folio.org/browse/UISACQCOMP-68 …
=> UISACQCOMP-68 v3.0.2 bugfix release

CHANGELOG.md, lib/constants/acqCommands.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UISACQCOMP-69 …
=> UISACQCOMP-69 Remove shortcut duplicates

CHANGELOG.md, lib/hooks/index.js, lib/hooks/useIntegrationConfigs/index.js, lib/hooks/useIntegrationConfigs/useIntegrationConfigs.js, lib/hooks/useIntegrationConfigs/useIntegrationConfigs.test.js
https://issues.folio.org/browse/UISACQCOMP-71 …
=> UISACQCOMP-71 Leverage useIntegrationConfigs hook

CHANGELOG.md, lib/hooks/index.js, lib/hooks/useOrganization/index.js, lib/hooks/useOrganization/useOrganization.js, lib/hooks/useOrganization/useOrganization.test.js
https://issues.folio.org/browse/UISACQCOMP-72 …
=> UISACQCOMP-72 Leverage useOrganization hook from ui-organizations

CHANGELOG.md, lib/FindRecords/FindRecords.js, lib/FindRecords/FindRecords.test.js, lib/FindRecords/FindRecordsModal.css, lib/FindRecords/FindRecordsModal.js, lib/FindRecords/hooks/index.js, lib/FindRecords/hooks/useRecordsSelect/index.js, lib/FindRecords/hooks/useRecordsSelect/useRecordsSelect.js, lib/FindRecords/index.js, lib/index.js, test/jest/babel.config.js
https://issues.folio.org/browse/UISACQCOMP-70 …
=> UISACQCOMP-70 FindRecords implementation

CHANGELOG.md, lib/AcqList/hooks/useFilters.js, lib/FindRecords/FindRecords.js, lib/FindRecords/FindRecordsModal.js, lib/LocationFilter/LocationFilter.test.js
https://issues.folio.org/browse/UISACQCOMP-74 …
=> UISACQCOMP-74 Add initial filters for FindRecords

CHANGELOG.md, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UISACQCOMP-75 …
=> UISACQCOMP-75 'Server address' validation not clear

CHANGELOG.md, lib/AcqList/hooks/useFilters.js
https://issues.folio.org/browse/UISACQCOMP-76 …
=> UISACQCOMP-76 Search normalization to handle trailing space

CHANGELOG.md, lib/AcqList/utils/queryUtils.js, lib/AcqUnitFilter/AcqUnitFilter.js, lib/constants/constants.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UISACQCOMP-77 …
=> UISACQCOMP-77 Update acquisitions unit filter to allow filtering on no acquisitions unit

CHANGELOG.md, lib/FolioFormattedDate/FolioFormattedDate.js
https://issues.folio.org/browse/UISACQCOMP-78 …
=> UISACQCOMP-78 timezone support in FolioFormattedDate

CHANGELOG.md, lib/hooks/index.js, lib/hooks/usePaneFocus/index.js, lib/hooks/usePaneFocus/usePaneFocus.js, lib/hooks/usePaneFocus/usePaneFocus.test.js
https://issues.folio.org/browse/UISACQCOMP-79 …
=> UISACQCOMP-79 useFocusPane hook

lib/FilterSearchInput/FilterSearchInput.js
https://issues.folio.org/browse/UISACQCOMP-80 …
=> UISACQCOMP-80 Fix autofocus issue after loading

CHANGELOG.md, lib/AcqList/NoResultsMessage/NoResultsMessage.js, lib/FindRecords/FindRecordsModal.js, lib/PluginFindRecord/PluginFindRecordModal.js, lib/hooks/useShowCallout/readme.md, lib/hooks/useShowCallout/useShowCallout.js, lib/utils/validateURL/validateURL.js, package.json
https://issues.folio.org/browse/UISACQCOMP-81 …
=> Release v3.1.0

CHANGELOG.md, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.js, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.test.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UISACQCOMP-83 …
=> UISACQCOMP-83 Display only active funds

CHANGELOG.md, lib/AcqList/ResultsPane/ResultsPane.js, lib/AcqList/hooks/index.js, lib/AcqList/hooks/useResultsSRStatus/index.js, lib/AcqList/hooks/useResultsSRStatus/useResultsSRStatus.js, lib/AcqList/hooks/useResultsSRStatus/useResultsSRStatus.test.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UISACQCOMP-89 …
=> UISACQCOMP-89 Results List pane should announce results count change

CHANGELOG.md, lib/AcqUnitFilter/AcqUnitFilter.js
https://issues.folio.org/browse/UISACQCOMP-90 …
=> UISACQCOMP-90 Fix acqUnit filter

CHANGELOG.md, package.json
https://issues.folio.org/browse/UISACQCOMP-91 …
=> UISACQCOMP-91 release v3.1.1

CHANGELOG.md, lib/AcqList/utils/queryUtils.js, lib/AcqList/utils/queryUtils.test.js, lib/NumberRangeFilter/NumberRangeFilter.js, lib/NumberRangeFilter/NumberRangeFilter.test.js, lib/NumberRangeFilter/index.js, lib/index.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UISACQCOMP-88 …
=> UISACQCOMP-88 Create Number range filter

CHANGELOG.md, package.json
https://issues.folio.org/browse/UISACQCOMP-92 …
=> UISACQCOMP-92 Remove react-hot-loader

CHANGELOG.md, lib/ExchangeRateValue/ExchangeRateValue.js, lib/ExchangeRateValue/useExchangeRateValue.js, lib/ExchangeRateValue/useExchangeRateValue.test.js, lib/FieldHolding/FieldHolding.js, lib/FieldHolding/FieldHolding.test.js, lib/shapes/fieldSelectOptions.js
https://issues.folio.org/browse/UISACQCOMP-98 …
=> UISACQCOMP-98 module warnings analysis

CHANGELOG.md, lib/DynamicSelection/DynamicSelection.js, lib/DynamicSelection/DynamicSelection.test.js, lib/DynamicSelection/index.js, lib/DynamicSelectionFilter/DynamicSelectionFilter.js, lib/DynamicSelectionFilter/DynamicSelectionFilter.test.js, lib/DynamicSelectionFilter/index.js, lib/index.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UISACQCOMP-103 …
=> UISACQCOMP-103 Add new component for dynamic data loading and filtering

CHANGELOG.md, lib/OptimisticLockingBanner/OptimisticLockingBanner.js, lib/OptimisticLockingBanner/OptimisticLockingBanner.test.js, lib/OptimisticLockingBanner/index.js, lib/constants/constants.js, lib/index.js
https://issues.folio.org/browse/UISACQCOMP-104 …
=> UISACQCOMP-104 Add common OptimisticLockingBanner

CHANGELOG.md, lib/DragDropMCL/DragDropMCL.css, lib/DragDropMCL/DragDropMCL.js, lib/DragDropMCL/DragDropMCL.test.js, lib/DragDropMCL/DraggableRow/DraggableRow.js, lib/DragDropMCL/DraggableRow/DraggableRow.test.js, lib/DragDropMCL/DraggableRow/index.js, lib/DragDropMCL/DraggableRowFormatter/DraggableRowFormatter.js, lib/DragDropMCL/DraggableRowFormatter/DraggableRowFormatter.test.js, lib/DragDropMCL/DraggableRowFormatter/index.js, lib/DragDropMCL/constants.js, lib/DragDropMCL/index.js, lib/index.js, package.json, test/jest/__mock__/beautifulDND.mock.js, test/jest/__mock__/index.js
https://issues.folio.org/browse/UISACQCOMP-105 …
=> UISACQCOMP-105 Add a common Drag-n-Drop MCL component

CHANGELOG.md, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinalContainer.js
https://issues.folio.org/browse/UISACQCOMP-106 …
=> UISACQCOMP-106 remove encumbrance when change fund

CHANGELOG.md, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.js, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinalContainer.js, lib/FundDistribution/FundDistributionFields/handleValidationErrorResponse.js, lib/FundDistribution/FundDistributionFields/handleValidationErrorResponse.test.js, lib/FundDistribution/FundDistributionFields/validateFundDistributionFinal.js, lib/FundDistribution/FundDistributionFields/validateFundDistributionFinal.test.js, lib/RepeatableFieldWithErrorMessage/RepeatableFieldWithValidation.js, lib/hooks/index.js, lib/hooks/useAsyncDebounce/index.js, lib/hooks/useAsyncDebounce/useAsyncDebounce.js, lib/hooks/useAsyncDebounce/useAsyncDebounce.test.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UISACQCOMP-111 …
=> UISACQCOMP-111 Add support for backend fund distribution total validation

CHANGELOG.md, lib/FindRecords/FindRecordsModal.js, lib/FindRecords/hooks/useRecordsSelect/useRecordsSelect.js, lib/constants/constants.js
https://issues.folio.org/browse/UISACQCOMP-116 …
=> UISACQCOMP-116 Support MCL Next/Previous pagination by plugins

lib/constants/constants.js
https://issues.folio.org/browse/UISACQCOMP-116 …
=> UISACQCOMP-116 Set results count equals 50 for plugins

lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.js, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.test.js
https://issues.folio.org/browse/UINV-432 …
=> UINV-432 100% of total calculation is different on FE and BE

CHANGELOG.md, lib/AcqList/hooks/useLocalStorageFilters.js, lib/AcqList/hooks/useLocationFilters.js
https://issues.folio.org/browse/UISACQCOMP-118 …
=> UISACQCOMP-118 Selecting a new search index automatically kicks off a new search

CHANGELOG.md, package.json
https://issues.folio.org/browse/UISACQCOMP-119 …
=> Release v3.2.4

lib/FindRecords/FindRecords.js
https://issues.folio.org/browse/UISACQCOMP-116
- Add `id` prop to default trigger component …
=> UISACQCOMP-116 Add 'id' prop to default trigger

package.json
=> Set next minor version v3.4.0

CHANGELOG.md, lib/utils/filterSelectValues.js, lib/utils/filterSelectValues.test.js
https://issues.folio.org/browse/UISACQCOMP-125
Escape RegExp special characters when filtering values in selection. …
=> UISACQCOMP-125 Orders POL location dropdown search textbox doesn't allow use of parentheses characters

CHANGELOG.md
=> Release v3.3.2

CHANGELOG.md, lib/VersionHistory/VersionCard/VersionCard.css, lib/VersionHistory/VersionCard/VersionCard.js, lib/VersionHistory/VersionCard/VersionCard.test.js, lib/VersionHistory/VersionCard/index.js, lib/VersionHistory/VersionHistoryPane/VersionHistoryPane.js, lib/VersionHistory/VersionHistoryPane/VersionHistoryPane.test.js, lib/VersionHistory/VersionHistoryPane/index.js, lib/VersionHistory/getFieldLabels.js, lib/VersionHistory/getFieldLabels.test.js, lib/VersionHistory/hooks/index.js, lib/VersionHistory/hooks/useVersionsDifference/index.js, lib/VersionHistory/hooks/useVersionsDifference/useVersionsDifference.js, lib/VersionHistory/hooks/useVersionsDifference/useVersionsDifference.test.js, lib/VersionHistory/index.js, lib/hooks/index.js, lib/hooks/useUsersBatch/index.js, lib/hooks/useUsersBatch/useUsersBatch.js, lib/hooks/useUsersBatch/useUsersBatch.test.js, lib/utils/index.js, lib/utils/objectDifference/index.js, lib/utils/objectDifference/objectDifference.js, lib/utils/objectDifference/objectDifference.test.js, test/jest/fixtures/orderLineAuditEvent.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UISACQCOMP-131
- add util which will return difference between two JSON-like objects (`objectDifference.js`). It will deep compare objects and return a list of changes (create, update, delete), including changed fields paths;
<details open>
<summary>Example</summary>
```
// E.g. 
const obj1 = {
foo: {
bar: [{ value: 42 }],
},
baz: 'hello',
};
const obj2 = {
fizz: 'buzz'
foo: {
bar: [{ value: 43 }],
},
};
objectDifference(obj1, obj2)
/* Returns:
[
{ type: 'create', path: 'fizz', values: [undefined, 'buzz'] }, // values: [oldValue, newValue] 
{ type: 'update', path: 'foo.bar[0].value', values: [42, 43] },
{ type: 'delete', path: 'baz', values: ['hello', undefined] },
]
*/
```
</details>
---
- add hook, which will return a list of changed fields for each …
=> UISACQCOMP-131 Display all versions in change log in fourth pane

lib/VersionHistory/VersionCard/VersionCard.js, lib/VersionHistory/VersionCard/VersionCard.test.js, lib/VersionHistory/VersionHistoryPane/VersionHistoryPane.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UIOR-858?focusedCommentId=152071&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-152071
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
=> UISACQCOMP-131 Update card related labels

lib/VersionHistory/VersionHistoryPane/VersionHistoryPane.js, translations/stripes-acq-components/en.json
User group eventually decided to replace label for lost records with "Record deleted"
https://issues.folio.org/browse/UIOR-1036?focusedCommentId=152419&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-152419 …
=> UISACQCOMP-131 UIOR-1036 Replace 'Data lost' label with 'Record deleted'

CHANGELOG.md, lib/ContributorDetails/ContributorDetails.js, lib/ContributorDetails/ContributorDetailsContainer.js, lib/FundDistribution/FundDistributionView/FundDistributionView.js, lib/FundDistribution/FundDistributionView/FundDistributionViewContainer.js, lib/FundDistribution/FundDistributionView/constants.js, lib/FundDistribution/FundDistributionView/index.js, lib/ProductIdDetails/ProductIdDetails.js, lib/ProductIdDetails/ProductIdDetailsContainer.js, lib/VendorReferenceNumbers/VendorReferenceNumbersDetails/VendorReferenceNumbersDetails.js, lib/VersionHistory/VersionHistoryPane/VersionHistoryPane.js, lib/VersionHistory/VersionHistoryPane/VersionHistoryPane.test.js
https://issues.folio.org/browse/UISACQCOMP-132
Add ability to provide MCL props for some common components …
=> UISACQCOMP-132 Show in version history record view, which fields have been edited

CHANGELOG.md, lib/AcqList/NoResultsMessage/NoResultsMessage.js, lib/AcqList/hooks/useFiltersToogle/useFiltersToogle.js, lib/hooks/useToggle/useToggle.js
https://issues.folio.org/browse/UISACQCOMP-136
- add `notLoadedMessage` prop for `<NoResultsMessage>`. This will add ability to provide custom message;
- use `useCallback` from react in `useToggle` and `useFiltersToogle` hooks to reduce redundant rerenders.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
=> UISACQCOMP-136 Add ability to provide `notLoadedMessage` prop for `<NoResultsMessage>` component

CHANGELOG.md, lib/VersionHistory/VersionHistoryPane/VersionHistoryPane.js, lib/VersionHistory/VersionHistoryPane/VersionHistoryPane.test.js, package.json
https://issues.folio.org/browse/UISACQCOMP-139
Some actions cause additional events in the audit log that do not contain meaningful changes.
---
[UISACQCOMP-140](https://issues.folio.org/browse/UISACQCOMP-140)
bump stripes to 8.0.0 for Orchid/2023-R1 …
=> UISACQCOMP-139 Do not display version history cards without changes

CHANGELOG.md, lib/AcqList/ResultsPane/ResultsPane.js
=> UISACQCOMP-144 acq list result pane doesn't support icons

CHANGELOG.md, package.json
=> UISACQCOMP-138 unpin @rehooks/local-storage

CHANGELOG.md, lib/FindRecords/FindRecords.test.js, lib/Organization/OrganizationValue/OrganizationValue.js, lib/Organization/OrganizationValue/OrganizationValueContainer.js, lib/Organization/OrganizationValue/OrganizationValueContainer.test.js, test/jest/__mock__/index.js, test/jest/__mock__/reactVirtualizedAutoSize.mock.js
https://issues.folio.org/browse/UISACQCOMP-147
https://issues.folio.org/browse/UIOR-1055
- Add `isLink` to identify if the value should be the link to the related organization
- Mock `react-virtualized-auto-sizer` to resolve tests [issues](https://folio-project.slack.com/archives/CAN13SWBF/p1680489209348879)
- Update unit tests
Ideally all of the PRs …
=> UISACQCOMP-147 Link to vendor organization record from organization value

CHANGELOG.md, lib/AcqList/hooks/useLocationSorting.js
Add dependencies argument in the custom hook useLocationSorting
[UISACQCOMP-149](https://issues.folio.org/browse/UISACQCOMP-149)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
=> UISACQCOMP-149: Add dependencies argument in the custom hook useLocationSorting

CHANGELOG.md, lib/FundDistribution/FundDistributionView/FundDistributionView.js, lib/FundDistribution/FundDistributionView/FundDistributionView.test.js
https://issues.folio.org/browse/UISACQCOMP-150
Display `<NoValue>` (`-`) as a text, not a link …
=> UISACQCOMP-150 'No value' in the 'Current encumbrance' column of a fund distribution field is a hyperlink

lib/FundDistribution/FundDistributionView/FundDistributionView.js, lib/FundDistribution/FundDistributionView/FundDistributionView.test.js
https://issues.folio.org/browse/UISACQCOMP-150
Improvement of https://github.com/folio-org/stripes-acq-components/pull/699
If an amount equals `0`, it also should be a link to encumbrance.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
=> UISACQCOMP-150 Update the condition to convert to a link

CHANGELOG.md, lib/hooks/useFrontendPaginatedData/index.js, lib/hooks/useFrontendPaginatedData/useFrontendPaginatedData.js, lib/hooks/useFrontendPaginatedData/useFrontendPaginatedData.test.js, lib/hooks/useLocalPagination/index.js, lib/hooks/useLocalPagination/useLocalPagination.js, lib/hooks/useLocalPagination/useLocalPagination.test.js
[UISACQCOMP-153](https://issues.folio.org/browse/UISACQCOMP-153)
- add custom hooks to handle local pagination …
=> UISACQCOMP-153: add local pagination hook

package.json, test/jest/babel.config.js
=> replace @babel packages that have moved from proposed to official

CHANGELOG.md, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.js, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.test.js
[UISACQCOMP-156](https://issues.folio.org/browse/UISACQCOMP-156)
- run validation on change fundId
- Check the expanse class id field before submitting the form to be saved.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
=> UISACQCOMP-156 - prevent form to be saved with empty expanse class id.

lib/hooks/useUsersBatch/useUsersBatch.js
=> UISACQCOMP-131 do not re-create default value in useUserBatch

lib/Donors/DonorsContainer.js, lib/Donors/DonorsLookup.js
[UISACQCOMP-168](https://issues.folio.org/browse/UISACQCOMP-168) - add `columnWidths` to fix column issue
https://github.com/folio-org/stripes-acq-components/assets/116072773/3aa50a68-67a9-45d5-9bac-dffeea915d46
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> UISACQCOMP-168: add default columnWidths for donors list

lib/Donors/utils.js, lib/Donors/utils.test.js
[UISACQCOMP-166](https://issues.folio.org/browse/UISACQCOMP-166) - donor name should NOT be a link when `canViewOrganizations` is `false`
https://github.com/folio-org/stripes-acq-components/assets/116072773/db325600-bf0e-47cf-9653-8d6797784028 …
=> UISACQCOMP-166: fix organizations' list

lib/PrivilegedDonorContacts/PrivilegedDonorContactsLookup.js, lib/PrivilegedDonorContacts/PrivilegedDonorContactsLookup.test.js
…o edit privileged donor contacts
[UISACQCOMP-172](https://issues.folio.org/browse/UISACQCOMP-172) - UISACQCOMP-172: disable add donor button if there is no permissions to edit privileged donor contacts …
=> UISACQCOMP-172: disable add donor button if there is no permissions to edit privileged donor contacts

CHANGELOG.md, lib/PrivilegedDonorContacts/ContactsContainer.js, lib/PrivilegedDonorContacts/utils.js, lib/VersionHistory/VersionHistoryPane/VersionHistoryPane.js, lib/VersionHistory/constants.js, lib/VersionHistory/getFieldLabels.js, lib/VersionHistory/getFieldLabels.test.js
[UISACQCOMP-173](https://issues.folio.org/browse/UISACQCOMP-173) - hide donors modal and improve `getFieldLabels` function
https://github.com/folio-org/ui-orders/assets/116072773/645cd298-8de7-4ab6-a9a8-9314372a3df5
- hide donors lookup modal if user doesn't have permission to edit
- add missing field names and exclude if not part of the fields mapping …
=> UISACQCOMP-173: Edit `getFieldLabels` util function to improve PO & POL version history fields

CHANGELOG.md, lib/FieldHolding/useHoldings.js, lib/constants/api.js, lib/constants/piece.js, lib/hooks/index.js, lib/hooks/useLineHoldings/useLineHoldings.js, lib/hooks/useOrderLine/index.js, lib/hooks/useOrderLine/useOrderLine.js, lib/hooks/useOrderLine/useOrderLine.test.js, translations/stripes-acq-components/en.json
https://issues.folio.org/browse/UISACQCOMP-174
Update the dictionary of piece statuses to include new ones. Also for i18n, you should add translations.
Additional scope (to subsequently prevent code duplication):
- Move `holdings-storage/holdings` to a separate constant `HOLDINGS_API`, and update places where it used;
- Include `useOrderLine` hook in the lib (will be used in several acq modules);
- Are the JIRAs under active …
=> UISACQCOMP-174 Add support for the `Late`, `Claim delayed`, `Claim sent`, `Unreceivable` piece statuses

CHANGELOG.md, lib/utils/validateRequired.js, lib/utils/validateRequired.test.js, translations/stripes-acq-components/en.json
[UISACQCOMP-176](https://issues.folio.org/browse/UISACQCOMP-176) - Add min and max number validation
https://github.com/folio-org/stripes-acq-components/assets/116072773/84196c4d-89ae-4d5c-a89b-d147430c6e4d …
=> UISACQCOMP-176: Add min and max number validation

test/jest/__mock__/index.js, test/jest/__mock__/resizeObserver.mock.js
=> ResizeObserver mock

CHANGELOG.md, lib/utils/validateRequired.js, lib/utils/validateRequired.test.js, translations/stripes-acq-components/en.json
Propagate changes from develop branch
https://github.com/folio-org/stripes-acq-components/pull/748
=> Sprint 182 - UISACQCOMP-176

CHANGELOG.md, lib/CurrencyExchangeRateFields/CurrencyExchangeRateFields.js, lib/CurrencyExchangeRateFields/CurrencyExchangeRateFields.test.js, lib/CurrencyExchangeRateFields/CurrentExchangeRate/CurrentExchangeRate.js, lib/CurrencyExchangeRateFields/constants.js, lib/VisibilityControl/IfFieldVisible/IfFieldVisible.js, lib/VisibilityControl/IfFieldVisible/IfFieldVisible.test.js, lib/VisibilityControl/IfFieldVisible/index.js, lib/VisibilityControl/IfVisible/IfVisible.js, lib/VisibilityControl/IfVisible/IfVisible.test.js, lib/VisibilityControl/IfVisible/index.js, lib/VisibilityControl/VisibilityControl.css, lib/VisibilityControl/VisibilityControl.js, lib/VisibilityControl/VisibilityControl.test.js, lib/VisibilityControl/index.js, lib/index.js
[UISACQCOMP-178](https://folio-org.atlassian.net/browse/UISACQCOMP-178) - allow order template to hide Currency and exchange rate fields
- Has a related PR https://github.com/folio-org/ui-orders/pull/1551
https://github.com/folio-org/stripes-acq-components/assets/116072773/661e9c12-40ea-4519-ac98-2cc9c41fca3d
Ideally all of the PRs involved in breaking …
=> UISACQCOMP-178: allow order template to hide Currency and exchange rate fields

CHANGELOG.md, lib/ExchangeRateValue/ExchangeRateValue.js, lib/ExchangeRateValue/ExchangeRateValue.test.js, lib/hooks/index.js, lib/hooks/useExchangeRateValue/index.js, lib/hooks/useExchangeRateValue/useExchangeRateValue.js, lib/hooks/useExchangeRateValue/useExchangeRateValue.test.js
[UISACQCOMP-179](https://folio-org.atlassian.net/browse/UISACQCOMP-179)
related to this PR - https://github.com/folio-org/ui-invoice/pull/757 …
=> UISACQCOMP-179: Export `useExchangeRateValue` hook for reusability purposes

test/jest/__mock__/stripesCore.mock.js
=> Mock `<TitleManager>` from stripes-core

CHANGELOG.md, lib/constants/api.js, lib/constants/order.js, lib/hooks/index.js, lib/hooks/useCentralOrderingSettings/index.js, lib/hooks/useCentralOrderingSettings/useCentralOrderingSettings.js, lib/hooks/useCentralOrderingSettings/useCentralOrderingSettings.test.js
https://folio-org.atlassian.net/browse/UISACQCOMP-182 …
=> UISACQCOMP-182 Implement common tools to retrieve 'Central ordering' settings

CHANGELOG.md, jest.config.js, lib/AcqList/hooks/useLocationFilters.js, lib/AcqList/hooks/useLocationFilters.test.js, package.json
- UISACQCOMP-181 is added.
- Added PNG mocking to Jest config to fix tests failing. The errors occur because Jest, by default, doesn't understand imported assets like PNGs and tries to parse them as JavaScript. This is because of the newly added PNG file in [stripes-smart-component/ProfilePicture](https://github.com/folio-org/stripes-smart-components/blob/b14335d24dbc9d3cfb0fbee3d996ae42c5e32431/lib/ProfilePicture/ProfilePicture.js#L8).
- Do JIRAs exist to update the impacted …
=> Release v5.1.1

lib/RoutingList/RoutingList.js, lib/RoutingList/constants.js, lib/hooks/useUsersBatch/useUsersBatch.js
[UISACQCOMP-184](https://folio-org.atlassian.net/browse/UISACQCOMP-184) - add column width and disable button logic …
=> UISACQCOMP-184: add column width and disable button logic

lib/FieldHolding/FieldHolding.js, lib/FieldLocation/FieldLocationFinal.js, lib/constants/api.js, lib/hooks/consortia/index.js, lib/hooks/consortia/useConsortiumInstanceHoldings/index.js, lib/hooks/consortia/useConsortiumInstanceHoldings/useConsortiumInstanceHoldings.js, lib/hooks/consortia/useConsortiumInstanceHoldings/useConsortiumInstanceHoldings.test.js, lib/hooks/index.js, lib/hooks/useInstanceHoldingsQuery/index.js, lib/hooks/useInstanceHoldingsQuery/useInstanceHoldingsQuery.js, lib/hooks/useInstanceHoldingsQuery/useInstanceHoldingsQuery.test.js
https://folio-org.atlassian.net/browse/UISACQCOMP-190
Initial PR: #778 
In addition to loading the locations, information about consortium holdings also needs to be loaded. Therefore, a reusable hook should be implemented that will load holdings by instance id from the consortium.
https://github.com/folio-org/stripes-acq-components/assets/88109087/9e327fdb-44d0-44ef-8fc5-68a3571a881b
- Do …
=> UISACQCOMP-190 Implementation of components for loading consortium holdings

lib/RoutingList/RoutingListAccordion/RoutingListAccordion.js, lib/RoutingList/RoutingListAccordion/RoutingListAccordion.test.js, lib/RoutingList/hooks/useRoutingLists/useRoutingLists.js, lib/RoutingList/hooks/useRoutingLists/useRoutingLists.test.js
[UISACQCOMP-191](https://folio-org.atlassian.net/browse/UISACQCOMP-191): fix routing list accordion collapse issue
=> UISACQCOMP-191: fix routing list accordion collapse issue

lib/FindRecords/FindRecords.test.js, lib/FindRecords/FindRecordsModal.js
=> UISACQCOMP-194 fix tests

CHANGELOG.md, lib/FieldInventory/FieldInventory.js
[UISACQCOMP-204](https://folio-org.atlassian.net/browse/UISACQCOMP-204) - Add `locationLabelId` and `holdingLabelId` to `FieldInventory` Component
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
=> UISACQCOMP-204: Add `locationLabelId` and `holdingLabelId` to `FieldInventory` Component

CHANGELOG.md, lib/constants/item.js, translations/stripes-acq-components/en.json
[UISACQCOMP-205](https://folio-org.atlassian.net/browse/UISACQCOMP-205): Add translation for `Unavailable` item status message …
=> UISACQCOMP-205: Add translation for `Unavailable` item status message

lib/FieldHolding/utils.js, lib/LocationFilter/LocationFilter.js, lib/LocationFilter/LocationFilterContainer.js, lib/OrganizationFilter/PluggableOrganizationFilter.js
https://folio-org.atlassian.net/browse/UISACQCOMP-194
Central ordering in the receiving application implies the possibility of action within two tenants (central and active - system) without switching the active affiliation.
Note: main work was done in the scope of PR https://github.com/folio-org/stripes-acq-components/pull/784. The changelog was updated as well. This PR is aimed at improving missed gaps.
Update missed components (filters) to accept `tenantId` prop and properly behave on affiliation change.
- What other …
=> UISACQCOMP-194 Update filters to support central ordering search

CHANGELOG.md, lib/FieldHolding/FieldHolding.js, lib/FieldHolding/FieldHolding.test.js, lib/FindLocation/FindLocationLookup.js, lib/FindLocation/FindLocationLookup.test.js, lib/FindRecords/FindRecords.js, lib/FindRecords/FindRecordsModal.js
[UISACQCOMP-208](https://folio-org.atlassian.net/browse/UISACQCOMP-208): ECS - clear Select location filters on change another Affiliation
https://github.com/user-attachments/assets/9b9f1248-88e6-47e8-a7e1-5758e12a70ed
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> UISACQCOMP-208: ECS - clear Select location filters on change another Affiliation

.eslintrc, CHANGELOG.md, lib/FindLocation/FindLocation.test.js, lib/FindLocation/FindLocationLookup.js, lib/FindLocation/FindLocationLookup.test.js
https://folio-org.atlassian.net/browse/UISACQCOMP-202
https://github.com/user-attachments/assets/38aac5d3-c637-4ec1-9ca7-60d64ddd7102 …
=> UISACQCOMP-202 ECS - Display all consortium tenants in the affiliation selection of the location lookup

lib/utils/filterSelectValues.js
fix: `search is not a function` issue when an invalid reference is displayed on the selection
https://github.com/user-attachments/assets/014af871-0f1f-4544-8f8e-0bd6ebb151c8
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
=> fix: `search is not a function` issue

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, lib/Donors/DonorsLookup.js, lib/FindRecords/FindRecords.test.js, lib/FindRecords/FindRecordsModal.js, lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.test.js, package.json
Release [UISACQCOMP-212](https://folio-org.atlassian.net/browse/UISACQCOMP-212)
=> Release v5.1.2

test/jest/__mock__/index.js, test/jest/__mock__/stripesReactHotkeys.mock.js
Fix broken tests on release job
=> Mock @folio/stripes-react-hotkeys to fix tests

lib/FieldHolding/FieldHolding.js
=> UISACQCOMP-215 fix issue with cached holdings loading

CHANGELOG.md, package.json
https://folio-org.atlassian.net/browse/UISACQCOMP-245
https://folio-org.atlassian.net/browse/UISACQCOMP-246
=> UISACQCOMP-245 UISACQCOMP-246 Migrate react-intl and stripes dependencies

CHANGELOG.md, lib/hooks/useOrganization/useOrganization.js
https://folio-org.atlassian.net/browse/UISACQCOMP-252 …
=> UISACQCOMP-252 Include refetch for useOrganization hook

CHANGELOG.md, lib/claiming/hooks/useClaimsSend/useClaimsSend.js, lib/hooks/usePiecesStatusBatchUpdate/usePiecesStatusBatchUpdate.js
=> UISACQCOMP-256 Support tenantId in  and  hooks

CHANGELOG.md, lib/FindLocation/FindLocationLookup.js
https://folio-org.atlassian.net/browse/UISACQCOMP-257
Required by https://folio-org.atlassian.net/browse/UIF-561
Support the `assignedAffiliationsOnly` prop to determine if the tenant's list should be limited by a user's assigned affiliations.
https://github.com/user-attachments/assets/a39378da-e074-4241-aa7a-ae317379e772
Ideally all of the PRs involved in …
=> UISACQCOMP-257 Support for restriction on assigned affiliations

CHANGELOG.md, lib/SelectFilter/SelectFilter.js, lib/SelectFilter/SelectFilter.test.js, lib/SelectFilter/index.js, lib/index.js
https://folio-org.atlassian.net/browse/UISACQCOMP-260
https://github.com/user-attachments/assets/1f9b6422-1412-4ee3-a29c-9b9b029072eb …
=> UISACQCOMP-260 Implement filter based on stripes 'Select' component

CHANGELOG.md, lib/Credentials/CredentialsContext.css, lib/Credentials/CredentialsContext.js, lib/Credentials/CredentialsField/CredentialsField.js, lib/Credentials/CredentialsField/CredentialsField.test.js, lib/Credentials/CredentialsField/index.js, lib/Credentials/index.js, lib/constants/api.js, lib/hooks/index.js, lib/hooks/useExchangeRateSource/index.js, lib/hooks/useExchangeRateSource/useExchangeRateSource.js, lib/hooks/useExchangeRateSource/useExchangeRateSource.test.js, lib/index.js, lib/utils/api/api.test.js, lib/utils/api/fetchExchangeRateSource.js, lib/utils/api/index.js, test/jest/__mock__/stripesCore.mock.js, translations/stripes-acq-components/en.json
https://folio-org.atlassian.net/browse/UISACQCOMP-259
https://github.com/user-attachments/assets/fb3a07e6-9f32-4c70-bf04-e7e6713a984c …
=> UISACQCOMP-259 Create components to support exchange rate source feature

lib/PrivilegedDonorContacts/utils.js
=> UISACQCOMP-172 fix phone number mapping for privileged contacts

lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.js
=> UISACQCOMP-264 avoid undefined in onChange when onExpenseClassChange is not passed

lib/Credentials/CredentialsField/CredentialsField.js
https://folio-org.atlassian.net/browse/UISACQCOMP-259
Base PR - #874
=> UISACQCOMP-259 Use ACQ fields for the credentials

CHANGELOG.md, lib/Credentials/CredentialsField/CredentialsField.js
https://folio-org.atlassian.net/browse/UISACQCOMP-269
=> UISACQCOMP-269 Populate the key-value credential field based on the corresponding value from the form
