folio-org/stripes-acq-components

lib/AmountWithCurrencyField/AmountWithCurrencyField.js

If currency prop doesn't pass to `AmountWithCurrencyField`, it will use system currency (`stripes.currency`)  
add `stripes.currency` as default prop  for `AmountWithCurrencyField`
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …

UINV-12 Update currency prop

---

CHANGELOG.md
lib/utils/acqRowFormatter/acqRowFormatter.css
lib/utils/acqRowFormatter/acqRowFormatter.js
lib/utils/acqRowFormatter/acqRowFormatter.test.js
lib/utils/acqRowFormatter/index.js
lib/utils/index.js

`rowProps.alignLastColToEnd` is used as a flag
Align actions icons in table to right hand side of view pane(s)
https://issues.folio.org/browse/UINV-138
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …

UINV-138 Common style to align last column to the end

---

CHANGELOG.md
lib/PluginFindRecord/PluginFindRecordModal.js
translations/stripes-acq-components/en.json

https://issues.folio.org/browse/UIORGS-173
The "Select all"-checkbox in the find record modal does not have a discernable text or a screen reader friendly message which leaves screen reader users in the dark.
This small change adds an aria-label attribute for the checkbox which reads "Select all". 
Note: I kept the localized message very generic since this component is used for different purposes.

UIORGS-173: Added aria-label for the 'Select all' checkbox in the find record modal

---

CHANGELOG.md
lib/AmountWithCurrencyField/AmountWithCurrencyField.js
test/jest/__mock__/stripesCore.mock.js

Add mocks and display `AmountWithCurrencyField` as `NoValue` if no value is provided
https://issues.folio.org/browse/UIF-251 …

UIF-251 Update view pane to display null as hyphen

---

lib/AcqList/constants.js
lib/AcqList/utils/queryUtils.js
lib/AcqList/utils/queryUtils.test.js

user puts desired date in his timezone. for example, _2020-11-04_ in start and end dates. since we store datetimes in utc on back-end we can just convert to utc begin moment of day in _start_ input and final moment of day in _end_ input. So the filter query to back-end will be like `(metadata.createdDate>="2020-11-03T21:00:00.000" and metadata.createdDate<="2020-11-04T20:59:59.999")`
My local timezone is UTC+3
https://issues.folio.org/browse/UINV-202
- Do JIRAs exist to update …

UINV-202 fix by UTC datetime value

---

lib/AcqList/utils/queryUtils.js
lib/AcqList/utils/queryUtils.test.js

Basically, we need separate filter queries for date values and datetime. Datime should be converted in the UTC, dates should go as user entered, since it's the same as user enters them through calendar field
https://issues.folio.org/browse/UINV-202 …

UINV-202 introduce datetime and date range filters

---

lib/utils/formatDate.js

https://issues.folio.org/browse/UIREC-124
since we store dates always in utc0, it makes no sense to respect selected timezone in folio while showing them
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …

UIREC-124 default timezone to show dates is UTC0

---

package.json
test/jest/babel.config.js

* Update babel version used by jest/rtl to avoid errors related to: `ReferenceError: React is not defined` (clones https://github.com/folio-org/ui-inventory/pull/1396)
* Add missing @babel/preset-typescript dependency (follow-up to #493) …

UISACQCOMP-31-1 Update babel config for jest/rtl

---

CHANGELOG.md
lib/utils/getControlledVocabTranslations.js
lib/utils/getControlledVocabTranslations.test.js
lib/utils/index.js

https://issues.folio.org/browse/UISACQCOMP-123
To provide translations prop for `ControlledVocab` component we should pass an object whose keys are defined. So, to reduce a boilerplate we can use a function, that takes a root translation key as argument and return an object with translation keys as a result.
Ideally all of the PRs involved in breaking …

UISACQCOMP-123 Add common util which will provide translations for `ControlledVocab`

---

CHANGELOG.md
lib/PluginFindRecord/PluginFindRecordModal.js

* To use [react-highlight-words](https://github.com/bvaughn/react-highlight-words) with `ui-find-import-profile` plugin, we need to add handlers when search field is changed and reset all button is clicked.
* Added prop `onSearchChange` that calls when search field is changed and when `Reset all` button is clicked.
[PR UIPFIMP-52](https://github.com/folio-org/ui-plugin-find-import-profile/pull/129)
[Ticket UISACQCOMP-124](https://issues.folio.org/browse/UISACQCOMP-124)
- Do …

UISACQCOMP-124: Add handlers for search field and reset all button in PluginFindRecordModal component

---

lib/ContributorDetails/ContributorDetails.js
lib/ContributorDetails/ContributorDetailsContainer.js
lib/ExchangeRateValue/ExchangeRateValue.js
lib/FundDistribution/FundDistributionView/FundDistributionView.js
lib/FundDistribution/FundDistributionView/FundDistributionViewContainer.js
lib/FundDistribution/FundDistributionView/constants.js
lib/ProductIdDetails/ProductIdDetails.js
lib/ProductIdDetails/ProductIdDetailsContainer.js
lib/VendorReferenceNumbers/VendorReferenceNumbersDetails/VendorReferenceNumbersDetails.js
lib/VersionHistory/VersionHistoryPane/VersionHistoryPane.js
lib/VersionHistory/VersionHistoryPane/VersionHistoryPane.test.js
lib/VersionHistory/VersionViewContext/VersionViewContext.js
lib/VersionHistory/VersionViewContext/index.js
lib/VersionHistory/getHighlightedFields.js
lib/VersionHistory/getHighlightedFields.test.js
lib/VersionHistory/getVersionWrappedFormatter.js
lib/VersionHistory/getVersionWrappedFormatter.test.js
lib/VersionHistory/hooks/useVersionWrappedFormatter/index.js
lib/VersionHistory/hooks/useVersionWrappedFormatter/useVersionWrappedFormatter.js
lib/VersionHistory/hooks/useVersionWrappedFormatter/useVersionWrappedFormatter.test.js
lib/VersionHistory/index.js

https://issues.folio.org/browse/UISACQCOMP-132
1. Implement context (`<VersionViewContext />`) and provider (`<VersionViewContextProvider />`) components to get the data of the current version of the entity;
2. Add a utilities that will wrap the MCL result formatter and mark cells for related updated fields in the current version:
- `useVersionWrappedFormatter` hook - retrieve fields changes from version context and return updated formatter for MCLs based on `name` (field name in version snapshot), `fieldsMapping` (object map between MCL columns and MCL row field names), and `baseFormatter` (initial formatter to wrap). If there is no version context outside - returns base formatter;
- `getVersionWrappedFormatter` - return wrapped formatter that mark MCL cells- for updated fields;
- …

UISACQCOMP-132 Highlight changed values in MCLs for version view

---

CHANGELOG.md
lib/DynamicSelection/DynamicSelection.test.js
lib/DynamicSelectionFilter/DynamicSelectionFilter.test.js
package.json

- Refs https://issues.folio.org/browse/UISACQCOMP-137.
- Upgrade will be happening across all of Stripes framework and modules that reference react-redux.
- v7 to v8 is a very harmless upgrade and is only considered breaking since they removed a few rarely used functions (which I confirmed we don't use). See https://github.com/reduxjs/react-redux/releases/tag/v8.0.0 for more details.

UISACQCOMP-137 Upgrade react-redux to v8

---

CHANGELOG.md
lib/VersionHistory/VersionHistoryPane/VersionHistoryPane.test.js
lib/VersionHistory/VersionViewContext/VersionViewContext.js
lib/VersionHistory/getVersionWrappedFormatter.js
lib/VersionHistory/getVersionWrappedFormatter.test.js
lib/VersionHistory/hooks/useVersionWrappedFormatter/useVersionWrappedFormatter.js
lib/VersionHistory/hooks/useVersionsDifference/useVersionsDifference.js
lib/VersionHistory/hooks/useVersionsDifference/useVersionsDifference.test.js
lib/utils/objectDifference/index.js
lib/utils/objectDifference/objectDifference.js

https://issues.folio.org/browse/UISACQCOMP-143
The `objectDifference` comparison algorithm returns the path to the changed key in the object. But the Value of this key can also contain nested objects (including arrays) whose keys should be highlighted when the version history view is displayed.
When adding or removing a key from an object, the value of that key may not be the end value (primitive) that should be highlighted in the version history view, but a nested object or array. Therefore, for the version history, we need to get all the fields that have been added or removed.
If there are …

UISACQCOMP-143 Add the ability to get a list of all nested field names when comparing versions

---

CHANGELOG.md
lib/AcqList/utils/queryUtils.js
lib/AcqList/utils/queryUtils.test.js

https://issues.folio.org/browse/UISACQCOMP-145
If CQL query contains either `"` or `\` as it is (without escaping), then it may crush common requests to BE.
Add boolean parameter `escapeCql` for `buildFilterQuery` function and if it equals true then escape `\` and `"` in CQL search query. Thus, it remains possible to keep the string in its original form without escaping.
- Do PRs exist for …

UISACQCOMP-145 Escape quotes `"` and backslash `\` characters in search queries.

---

CHANGELOG.md
lib/AcqList/hooks/usePagination/usePagination.js
lib/AcqList/utils/searchUtils.js

https://issues.folio.org/browse/UISACQCOMP-148
In all ACQ apps, the state of the "Reset all" button relies on the location search: if the search is empty, the button is disabled. In addition to filters, a pagination hook also works with a search, which changes the search when changing filters or a page.
Keep the `search` empty when 'reset all' button was triggered.
- Do PRs exist for these …

UISACQCOMP-148 'Reset all' button remains enabled after clicking it to clear filtering results

---

CHANGELOG.md
lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinalContainer.js
lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinalContainer.test.js
lib/FundDistribution/FundDistributionFields/fetchExpenseClasses.js
package.json

[UISACQCOMP-151](https://issues.folio.org/browse/UISACQCOMP-151) - Allow user to select Fund and Expense class from Fiscal year specified in invoice.
Sub PR for the ticket https://github.com/folio-org/ui-invoice/pull/698
- pass `fiscalYearId` for `FundDistributionFieldsFinalContainer` component
- pass `formValues` for  `FundDistributionFieldsFinalContainer` component
- on `fiscalYearId` changes reset expanse class id if not belong to the current `fiscalYearId`
- ### [Video source](https://epam-my.sharepoint.com/:v:/p/alisher_musurmonov1/EYXZQrxtsfBKkqCHn8SqBr8BjcKBT_FoGAre9VVkdpH3dg?e=3RmFyT)
If …

UISACQCOMP-151 - get expanse classes with fiscalYearId

---

CHANGELOG.md
lib/AcqList/SingleSearchForm/SingleSearchForm.js

Add the ability to convey searchable indexes to the `Select` component via `children` prop, and not just through the `dataOptions` prop.
[UISACQCOMP-155](https://issues.folio.org/browse/UISACQCOMP-155)
[ui-inventory/pull/2195](https://github.com/folio-org/ui-inventory/pull/2195)
[stripes-components/pull/2090](https://github.com/folio-org/stripes-components/pull/2090)
https://github.com/folio-org/stripes-acq-components/assets/77053927/8a329286-8b78-445b-864a-a415c32d3372
- Do …

UISACQCOMP-155: Add the ability to convey searchable indexes to the Select component via children prop, and not just through the dataOptions prop.

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml
CHANGELOG.md
package.json

[UISACQCOMP-158](https://issues.folio.org/browse/UISACQCOMP-158) - Update `Node.js` to `v18` in GitHub Actions …

UISACQCOMP-158: Update `Node.js` to `v18` in GitHub Actions

---

CHANGELOG.md
lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.js
lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.test.js

[UISACQCOMP-159](https://issues.folio.org/browse/UISACQCOMP-159) - A user can not save edited PO line when budget without expense class was selected
- Prevent submit if the fields are not valid.
https://github.com/folio-org/stripes-acq-components/assets/116072773/4a974838-2cb4-4d82-8684-106ced07b7f2
Ideally all of the PRs involved in breaking changes would …

UISACQCOMP-159: fix A user can not save edited PO line issue

---

CHANGELOG.md
lib/CountryFilter/CountryFilter.js
lib/CountryFilter/CountryFilter.test.js

https://issues.folio.org/browse/UISACQCOMP-164
Countries are not correctly sorted in non-English locales.
Sort countries options in the filter.
https://github.com/folio-org/stripes-acq-components/assets/88109087/596aa888-6de3-48ad-94c2-a19689c423da …

UISACQCOMP-164 Sort the list of countries based on the current locale

---

CHANGELOG.md
lib/AcqList/SingleSearchForm/SingleSearchForm.js

Add inputType prop to <SingleSearchForm>
[UISACQCOMP-165](https://issues.folio.org/browse/UISACQCOMP-165)

UISACQCOMP-164 Add inputType prop to <SingleSearchForm> to make Inventory Browse search box a textarea

---

CHANGELOG.md
lib/AcqList/SingleSearchForm/SingleSearchForm.js

Added `indexRef` and `inputRef` props to `<SingleSearchForm>`
[UISACQCOMP-167](https://issues.folio.org/browse/UISACQCOMP-167)
https://github.com/folio-org/stripes-components/pull/2169
https://github.com/folio-org/ui-inventory/pull/2335

UISACQCOMP-167 Added `indexRef` and `inputRef` props to `<SingleSearchForm>`

---

lib/Donors/Donors.css
lib/Donors/DonorsContainer.js
lib/Donors/DonorsList.js
lib/Donors/DonorsListContainer.js
lib/Donors/DonorsListContainer.test.js
lib/Donors/constants.js
lib/Donors/index.js
lib/Donors/utils.js
lib/Donors/utils.test.js

[UISACQCOMP-166](https://issues.folio.org/browse/UISACQCOMP-166) - Updated default visible columns for the container. The purpose we don't need to pass the `unassignDonor` for form-based donors list. And move remove button on the right side of the row. …

UISACQCOMP-166: add `unassignDonor` to default formatters

---

CHANGELOG.md
lib/Donors/Donors.js
lib/Donors/Donors.test.js
lib/Donors/DonorsContainer.js
lib/Donors/DonorsContainer.test.js
lib/Donors/DonorsLookup.js
lib/Donors/constants.js
lib/Donors/hooks/useFetchDonors/useFetchDonors.js
lib/Donors/index.js
lib/Donors/utils.js
lib/Donors/utils.test.js

[UISACQCOMP-168](https://issues.folio.org/browse/UISACQCOMP-168) - 
Pass `onChange` and `onRemove` props for the `Donors` component in order to gain more control for complex use cases. The issue with the previous implementation was adding and removing the donors' list, controlled by the <Donors /> component. 
The proposed solution helps to pass donorOrganizationIds along with the mentioned props above in order to manage the list programmatically(conditionally).
Related issues - [UIOR-1148](https://issues.folio.org/browse/UIOR-1148)
https://github.com/folio-org/stripes-acq-components/assets/116072773/76239ef9-554e-4398-8e42-894d0f49ca66
- …

UISACQCOMP-168: extend `<Donors />` component props

---

lib/PrivilegedDonorContacts/PrivilegedDonorContactsLookup.js
lib/PrivilegedDonorContacts/PrivilegedDonorContactsLookup.test.js

[UISACQCOMP-172](https://issues.folio.org/browse/UISACQCOMP-172) - disable add donor button if user doesn't have permission to create privileged donor contacts
https://github.com/folio-org/stripes-acq-components/assets/116072773/b2554890-86a9-4b41-b224-ffdac9608da1
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …

UISACQCOMP-172: remove unused console log statement

---

CHANGELOG.md
lib/AcqList/hooks/useLocationFilters.js
lib/AcqList/hooks/useLocationFilters.test.js

Added new returned `clearLocationFilters` function from `useLocationFilters`
`useLocationFilters`’s `resetLocationFilters` function clears filters and query and qindex
In Inventory Browse we need to clear only filters when user selects different browse options
https://github.com/folio-org/stripes-acq-components/assets/19309423/fe310178-e687-4df0-9275-a46703b79ec0
[UISACQCOMP-181](https://folio-org.atlassian.net/browse/UISACQCOMP-181)

UISACQCOMP-181 Added new returned `clearLocationFilters` function from `useLocationFilters`

---

CHANGELOG.md
jest.config.js
lib/CustomFieldsFilters/CustomFieldsFilter.js
lib/CustomFieldsFilters/CustomFieldsFilter.test.js
lib/CustomFieldsFilters/CustomFieldsFilters.js
lib/CustomFieldsFilters/CustomFieldsFilters.test.js
lib/CustomFieldsFilters/README.md
lib/CustomFieldsFilters/index.js
lib/constants/constants.js
lib/index.js
test/jest/fixtures/customFields.js

https://folio-org.atlassian.net/browse/UISACQCOMP-183
Relocate `<CustomFieldsFilters>` and `<CustomFieldsFilter>` from [`ui-orders`](https://github.com/folio-org/ui-orders/tree/bc6c6da572aecd47c787d8c8f2d0e2d57abcc1a2/src/common/CustomFieldsFilters) to enable their reuse in other applications.

Add <CustomFieldsFilters> and <CustomFieldFilter> components

---

lib/hooks/useCentralOrderingSettings/useCentralOrderingSettings.js
lib/hooks/useCentralOrderingSettings/useCentralOrderingSettings.test.js

https://folio-org.atlassian.net/browse/UISACQCOMP-182
The central ordering setting stored only in the central tenant of a consortium, so we have to check this setting there even a user is currently in the member tenant.
Original PR #764 
Set central tenant as a `tenant` prop for the `useOkapyKy` hook.
Ideally all of the PRs involved in breaking changes …

UISACQCOMP-182 Send requests only in the central tenant in the `useCentralOrderingSettings` hook

---

CHANGELOG.md
lib/hooks/useToggle/useToggle.js

https://folio-org.atlassian.net/browse/UISACQCOMP-189
The state value returned by the `useState` hook only changes after a re-render, so the `toggle` function could recieve the "old state" instead of the current state, causing unexpected results. Therefore, to set a new state based on the previous one, we should use the state update function.
React docs:
- https://react.dev/reference/react/useState#ive-updated-the-state-but-logging-gives-me-the-old-value
- https://react.dev/learn/state-as-a-snapshot#state-over-time
Use [state updater function](https://react.dev/learn/queueing-a-series-of-state-updates) to "toggle" the current state.
- …

UISACQCOMP-189 Correctly manage state setting in the 'toggle' function of the 'useToggle' hook

---

CHANGELOG.md
lib/AcqList/hooks/useFilters.js
lib/AcqList/hooks/useFilters.test.js
lib/AcqList/hooks/useLocationFilters.js

Control the usage of the `trim` function during search change in `useFilters`.
Add a new flag `skipTrimOnChange` .
[UISACQCOMP-198](https://folio-org.atlassian.net/browse/UISACQCOMP-198)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …

UISACQCOMP-198: Introduce a new flag `skipTrimOnChange` to control the usage of the `trim` function during search change in `useFilters`.

---

CHANGELOG.md
lib/FieldInventory/FieldInventory.js
lib/RoutingList/RoutingListAccordion/RoutingListAccordion.js
lib/RoutingList/RoutingListAccordion/constants.js
lib/RoutingList/RoutingListEdit/RoutingListEdit.js
lib/RoutingList/RoutingListEdit/RoutingListEdit.test.js
lib/RoutingList/RoutingListView/RoutingListView.js
lib/RoutingList/hooks/useGoBack/useGoBack.js

UISACQCOMP-206 Replace fallbackPath by onClose in Routing Lists

---

CHANGELOG.md
lib/FieldHolding/FieldHolding.js

[UISACQCOMP-201](https://folio-org.atlassian.net/browse/UISACQCOMP-201):  ECS - clear Location/Holding field when affiliation selected
https://github.com/user-attachments/assets/ef1bd02f-789c-4205-a2f6-fb885962ec76
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …

UISACQCOMP-201:  ECS - clear Location/Holding field when affiliation selected

---

CHANGELOG.md
lib/FindLocation/FindLocationLookup.js

* Currently we get the list of tenants using `useCurrentUserTenants` hook. But in some cases we need to display all the member tenants except current and central one.
* Added new prop `customUserTenants`. If it's empty then use tenants from `useCurrentUserTenants` hook.
[UISACQCOMP-210](https://folio-org.atlassian.net/browse/UISACQCOMP-210)
Ideally all of …

UISACQCOMP-210: Support using custom list of tenants when open the locations modal

---

CHANGELOG.md
lib/Donors/DonorsLookup.js

Add isMultiSelect prop to DonorsLookup component to make it optional. It is needed to support https://folio-org.atlassian.net/browse/UIDATIMP-1656
- Add isMultiSelect prop to DonorsLookup component
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …

UISACQCOMP-212: Add isMultiSelect prop to DonorsLookup component

---

CHANGELOG.md
lib/ConsortiumFieldInventory/ConsortiumFieldInventory.js
lib/FieldHolding/FieldHolding.js
lib/FieldInventory/FieldInventory.js

[UISACQCOMP-215](https://folio-org.atlassian.net/browse/UISACQCOMP-215) - `isLoading` prop for holdings when fetching affiliation related locations to display loading indicator
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

UISACQCOMP-215: ECS - Add `isLoading` prop for holdings

---

lib/AcqUnitFilter/AcqUnitFilter.test.js
lib/AffiliationsSelection/AffiliationsSelection.test.js
lib/ConsortiumFieldInventory/ConsortiumFieldInventory.test.js
lib/CountryFilter/CountryFilter.test.js
lib/Currency/FieldCurrency/FieldCurrency.test.js
lib/CurrencyExchangeRateFields/CurrencyExchangeRateFields.test.js
lib/DeleteHoldingsModal/DeleteHoldingsModal.test.js
lib/DynamicSelection/DynamicSelection.test.js
lib/DynamicSelectionFilter/DynamicSelectionFilter.test.js
lib/FieldHolding/FieldHolding.test.js
lib/FieldLocation/FieldLocationFinal.test.js
lib/FieldLocation/FieldLocationFinalContainer.test.js
lib/FindLocation/FindLocationLookup.test.js
lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.test.js
lib/FundFilter/FundFilter.test.js
lib/LanguageFilter/LanguageFilter.test.js
lib/MaterialTypeFilter/MaterialTypeFilterContainer.test.js
lib/hooks/consortia/useConsortiumTenants/useConsortiumTenants.js

UISACQCOMP-202 avoid 10 limit when fetching tenants in locations lookup

---

CHANGELOG.md
lib/utils/errorHandling/ResponseErrorContainer.js
lib/utils/errorHandling/ResponseErrorContainer.test.js
lib/utils/errorHandling/ResponseErrorsContainer.js
lib/utils/errorHandling/ResponseErrorsContainer.test.js
lib/utils/errorHandling/index.js
lib/utils/index.js

https://folio-org.atlassian.net/browse/UISACQCOMP-219
- The ResponseErrorsContainer utility is designed to handle and manage errors that arise from HTTP responses in a structured way.
- It standardizes errors into a manageable format, regardless of whether the error comes in a specific format or is generic/unknown.
- It allows easy retrieval of error messages, codes, and handling via various strategies to streamline error processing.
- The utility simplifies working with multiple errors by storing them in a structured format, such as a `Map`.
1. The class encapsulates the original HTTP response and parses the response body, particularly focusing on extracting errors.
2. It provides both static and instance methods to:
- Parse errors, normalize them, and store them in a map for quick …

UISACQCOMP-219 Create common utilities for managing response errors

---

CHANGELOG.md
lib/VersionHistory/VersionHistoryPane/VersionHistoryPane.js

https://folio-org.atlassian.net/browse/UISACQCOMP-222 …

UISACQCOMP-222 Use `actionDate` value for version history card title instead of `eventDate`

---

CHANGELOG.md
lib/AcqDateRangeFilter/AcqDateRangeFilter.js
lib/AcqDateRangeFilter/AcqDateRangeFilter.test.js
package.json

Added new `subscribeOnReset` prop to `<AcqDateRangeFilter>`.
When reset event is called - clear date input fields.
https://github.com/user-attachments/assets/3e4d2612-f76e-4b8b-ac3f-b73d98ff64d1
[UISACQCOMP-227](https://folio-org.atlassian.net/browse/UISACQCOMP-227)
https://github.com/folio-org/stripes-authority-components/pull/172

UISACQCOMP-227 Added new `subscribeOnReset` prop to `<AcqDateRangeFilter>`

---

CHANGELOG.md
lib/AcqList/utils/queryUtils.js
lib/CustomFieldsFilters/CustomFieldsFilter.js
lib/CustomFieldsFilters/CustomFieldsFilters.js
lib/constants/api.js
lib/constants/constants.js
lib/hooks/index.js
lib/hooks/useAddresses/index.js
lib/hooks/useAddresses/useAddresses.js
lib/hooks/useAddresses/useAddresses.test.js
lib/utils/api/api.test.js
lib/utils/api/fetchOrderLines.js
lib/utils/api/fetchOrderLinesByIds.js
lib/utils/api/fetchOrders.js
lib/utils/api/fetchOrdersByIds.js
lib/utils/api/fetchOrganizations.js
lib/utils/api/fetchOrganizationsByIds.js
lib/utils/api/fetchPieces.js
lib/utils/api/fetchReceivingTitles.js
lib/utils/api/fetchReceivingTitlesByIds.js
lib/utils/api/index.js
lib/utils/getAddressOptions.js
lib/utils/index.js

https://folio-org.atlassian.net/browse/UISACQCOMP-228 …

UISACQCOMP-228 Add more reusable hooks and utilities

---

lib/AcqList/hooks/useFilters.js
lib/AcqList/hooks/useLocationFilters.js

https://folio-org.atlassian.net/browse/UICLAIM-1 **Scenario 4**
If the "default filters" parameter is present and there are no initial filters (from the URL), apply the default filters.
https://github.com/user-attachments/assets/e7fdd40f-3a1c-4ebf-a7e9-57e8ef4b19b4
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …

UISACQCOMP-228 Provide default filters for the `useLocationFilters` hook

---

lib/AcqList/hooks/useFilters.js

https://folio-org.atlassian.net/browse/UISACQCOMP-228?focusedCommentId=237472
regression of #829

UISACQCOMP-228 Revert changes in useFilters hook

---

CHANGELOG.md
lib/VersionHistory/components/VersionCheckbox/VersionCheckbox.js
lib/VersionHistory/components/VersionCheckbox/VersionCheckbox.test.js
lib/VersionHistory/components/VersionCheckbox/index.js
lib/VersionHistory/components/VersionKeyValue/VersionKeyValue.js
lib/VersionHistory/components/VersionKeyValue/VersionKeyValue.test.js
lib/VersionHistory/components/VersionKeyValue/index.js
lib/VersionHistory/components/VersionView/VersionView.js
lib/VersionHistory/components/VersionView/VersionView.test.js
lib/VersionHistory/components/VersionView/index.js
lib/VersionHistory/components/index.js
lib/VersionHistory/index.js
lib/constants/api.js
lib/hooks/useLineHoldings/useLineHoldings.js
lib/hooks/useOrganization/useOrganization.js
lib/hooks/useOrganization/useOrganization.test.js
lib/hooks/useUsersBatch/useUsersBatch.js
lib/hooks/useUsersBatch/useUsersBatch.test.js
translations/stripes-acq-components/en.json

https://folio-org.atlassian.net/browse/UISACQCOMP-230
Since the feature with the display of version history extends to other applications, a single source of common components for displaying versions and highlighting changed fields is required.
Based on the implementation of the feature in `ui-orders`, derive a set of common utilities and components. …

UISACQCOMP-230 Move reusable version history components to the ACQ lib

---

CHANGELOG.md
lib/DynamicSelection/DynamicSelection.js
lib/DynamicSelection/DynamicSelection.test.js
lib/DynamicSelectionFilter/DynamicSelectionFilter.test.js
lib/hooks/index.js
lib/hooks/useDebouncedQuery/index.js
lib/hooks/useDebouncedQuery/useDebouncedQuery.js
lib/hooks/useDebouncedQuery/useDebouncedQuery.test.js

[UISACQCOMP-233](https://folio-org.atlassian.net/browse/UISACQCOMP-233): add `useDebouncedQuery` hook to fix endless request for `DynamicSelection` component
https://github.com/user-attachments/assets/6ee5d906-b36e-42ea-89ee-3bdc0e6986b5 …

UISACQCOMP-233: add `useDebouncedQuery` hook to fix endless request for `DynamicSelection` component

---

lib/VersionHistory/components/VersionKeyValue/VersionKeyValue.js
lib/VersionHistory/getFieldLabels.js
lib/hooks/useCategories/useCategories.js

https://folio-org.atlassian.net/browse/UISACQCOMP-230 …

UISACQCOMP-230 Fix version history label resolving

---

CHANGELOG.md
lib/LocationFilter/LocationFilterContainer.js

https://folio-org.atlassian.net/browse/UISACQCOMP-239
This pull request enhances the `stripes-acq-components` module by updating the location filtering functionality to support cross-tenant environments. 
**Key Changes:**
- **Cross-Tenant Location Retrieval:** When the `crossTenant` parameter is set to `true`, the location filter now retrieves locations from all tenant members, enabling more comprehensive data access across multiple tenants.
https://github.com/user-attachments/assets/2be8bf1a-fb74-425c-852d-7f0658f3d81e
- …

UISACQCOMP-239 Claim locations from all members for locations filter when `crossTenant` equals `true`

---

CHANGELOG.md
lib/utils/invoiceExport/getInvoiceExportData.js
lib/utils/invoiceExport/getInvoiceExportData.test.js

https://folio-org.atlassian.net/browse/UISACQCOMP-237
https://github.com/user-attachments/assets/0b1bad95-0a86-4582-9f07-36b2f58a33a0 …

UISACQCOMP-237 Exclude unsupported currencies

---

CHANGELOG.md
lib/FieldTags/FieldTagsContainer.js
lib/FieldTags/FieldTagsFinal.js
lib/FileUploader/FileUploader.js
package.json

https://folio-org.atlassian.net/browse/UISACQCOMP-243
When used in the table there is no need for label to be rendered. 
In current implementation there is no option to hide it.
Introduce labelless prop
Without labelless prop
With labelless prop …

 UISACQCOMP-243 Add labelless prop to FieldTags component to hide label

---

CHANGELOG.md
lib/FieldHolding/utils.js

* When using the Update Ownership action on an Item, it would be helpful for the Holdings dropdown in the resulting modal to include Copy Number for a given holdings. The reason being that sometimes a library will have multiple holdings with matching Location and Call Number. Displaying the call number would help users differentiate between such Holdings and aid in choosing the correctly for their given scenario.
[STACQCOMP-253](https://folio-org.atlassian.net/browse/UISACQCOMP-253)
- What other modules will these changes …

STACQCOMP-253: Display Holdings copy number when selecting holding

---

CHANGELOG.md
lib/contexts/CentralOrderingContext.js

https://folio-org.atlassian.net/browse/UISACQCOMP-262
An error in getting central ordering settings should not be propagated to the error boundary and crash the app. Instead, the app should consider that central ordering is disabled and work normally.
- Provide a specific query key to the `useCentralOrderingSettings` hook;
- Provide `throwOnError` prop to make it possible to throw error to the "ErrorBoundary" if needed;
- Provide `suspense` prop.
- Do JIRAs exist to update the …

UISACQCOMP-262 Enhance `CentralOrderingContextProvider` component

---

lib/Credentials/CredentialsContext.js

https://folio-org.atlassian.net/browse/UISACQCOMP-259
The `<IfPermission>` component requires a mandatory `perm` prop. However, the current implementation of "credentials" components allows usage without explicitly passing permissions, which leads to an error when `perm` is missing.  
This PR adds a check to ensure `perm` is present before rendering `<IfPermission>`, preventing runtime errors.

UISACQCOMP-259 Fix render without required perm

---

CHANGELOG.md
lib/VisibilityControl/IfFieldVisible/IfFieldVisible.js
lib/VisibilityControl/IfFieldVisible/IfFieldVisible.test.js
lib/VisibilityControl/IfFieldVisible/index.js
lib/VisibilityControl/IfVisible/IfVisible.js
lib/VisibilityControl/IfVisible/IfVisible.test.js
lib/VisibilityControl/IfVisible/index.js

https://folio-org.atlassian.net/browse/UISACQCOMP-268
The `react-final-form` provides hooks that trigger re-renders to an infinite loop.
Use `FormSpy` to subscribe to `errors` changes and update the visibility state based on received errors.

UISACQCOMP-268 Optimize 'IfFieldVisible' component to reduce number of renders
